#!/usr/bin/env python3
"""tools/gen_baseline_board.py — Generate the 81-card baseline suite.

The Game 17 board (6 helpers, 23 cards) is the fixed fixture.
For each of the 81 remaining cards in the double deck, run the
BFS solver and record: solvable/no_plan, plan lines, timing.

Outputs (paths relative to the repo root):
  games/lynrummy/conformance/scenarios/baseline_board_81.dsl
  games/lynrummy/python/baseline_board_81_timing.json

Run from the python/ directory:
  python3 tools/gen_baseline_board.py

Commit both output files. Re-run after solver changes to update
the baseline; regenerate conformance fixtures with ops/check-conformance.
"""

import json
import os
import sys

# Resolve python/ dir so imports work regardless of cwd.
_PYTHON_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _PYTHON_DIR)

from buckets import Buckets
from rules.card import RANKS, SUITS
from rules.card import card as make_card
from bench_timing import time_solver


# ── Fixed board ──────────────────────────────────────────────────────────────

# The Game 17 standard opening board (23 deck-0 cards).
_BOARD_STACKS = [
    ["KS", "AS", "2S", "3S"],
    ["TD", "JD", "QD", "KD"],
    ["2H", "3H", "4H"],
    ["7S", "7D", "7C"],
    ["AC", "AD", "AH"],
    ["2C", "3D", "4C", "5H", "6S", "7H"],
]

# Verbatim DSL helper block (same every scenario).
_DSL_HELPERS = """\
  helper:
    at (0,0): KS AS 2S 3S
    at (0,0): TD JD QD KD
    at (0,0): 2H 3H 4H
    at (0,0): 7S 7D 7C
    at (0,0): AC AD AH
    at (0,0): 2C 3D 4C 5H 6S 7H"""


# ── Card helpers ──────────────────────────────────────────────────────────────

def _board_set():
    return {make_card(lbl, deck=0) for stack in _BOARD_STACKS for lbl in stack}


def _all_remaining():
    """All 81 (value, suit, deck) tuples not on the board, sorted."""
    on_board = _board_set()
    out = []
    for si in range(4):            # suits: C D S H
        for vi in range(13):       # values: A 2 … K
            for deck in (0, 1):
                c = (vi + 1, si, deck)
                if c not in on_board:
                    out.append(c)
    return out


def _dsl_label(c):
    """'2S' (deck 0) or '2S'' (deck 1)."""
    v, s, d = c
    base = RANKS[v - 1] + SUITS[s]
    return f"{base}'" if d else base


def _scenario_id(c):
    """Stable identifier: baseline_board_2S or baseline_board_2Sp."""
    v, s, d = c
    base = RANKS[v - 1] + SUITS[s]
    return f"baseline_board_{base}p" if d else f"baseline_board_{base}"


def _helpers_as_tuples():
    return [[make_card(lbl, deck=0) for lbl in stack] for stack in _BOARD_STACKS]


# ── Solver ────────────────────────────────────────────────────────────────────

def _time_solve(trouble_card):
    """Run solver via `bench_timing.time_solver` (warmup + GC-controlled
    min-of-10). Returns (plan_or_None, min_ms)."""
    helpers = _helpers_as_tuples()
    state = Buckets(helpers, [[trouble_card]], [], [])
    return time_solver(state)


# ── DSL formatting ────────────────────────────────────────────────────────────

def _format_scenario(c, plan):
    label = _dsl_label(c)
    sid = _scenario_id(c)

    if plan is None:
        result_desc = "no plan"
        expect = "  expect: no_plan"
    else:
        n = len(plan)
        result_desc = f"{n}-step plan"
        lines = "\n".join(f'      - "{line}"' for line, _ in plan)
        expect = f"  expect:\n    plan_lines:\n{lines}"

    desc = f"Baseline board, trouble {label}. {result_desc}. Auto-generated."
    return (
        f"scenario {sid}\n"
        f"  desc: {desc}\n"
        f"  op: solve\n"
        f"{_DSL_HELPERS}\n"
        f"  trouble:\n"
        f"    at (0,0): {label}\n"
        f"{expect}\n"
    )


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    repo_root = os.path.dirname(os.path.dirname(os.path.dirname(_PYTHON_DIR)))
    dsl_out = os.path.join(
        repo_root,
        "games/lynrummy/conformance/scenarios/baseline_board_81.dsl",
    )
    timing_out = os.path.join(_PYTHON_DIR, "baseline_board_81_timing.json")

    cards = _all_remaining()
    assert len(cards) == 81, f"Expected 81, got {len(cards)}"

    timing = {}
    header = (
        "# AUTO-GENERATED by tools/gen_baseline_board.py. Do not hand-edit.\n"
        "# Baseline suite: Game 17 board (6 helpers, 23 cards),\n"
        "# one trouble singleton per remaining card in the double deck (81 total).\n"
        "# Re-run the generator after solver changes, then commit both outputs.\n"
    )
    blocks = [header]

    for i, c in enumerate(cards):
        label = _dsl_label(c)
        sid = _scenario_id(c)
        print(f"[{i+1:2}/81] {label:<5} ... ", end="", flush=True)

        plan, ms = _time_solve(c)
        result_str = "no_plan" if plan is None else f"{len(plan)}-step plan"
        print(f"{result_str:<18}  {ms:7.1f}ms")

        blocks.append(_format_scenario(c, plan))
        timing[sid] = {
            "ms": round(ms, 1),
            "result": "no_plan" if plan is None else f"plan_{len(plan)}",
        }

    with open(dsl_out, "w") as f:
        f.write("\n".join(blocks))
    print(f"\nWrote {dsl_out}  ({len(cards)} scenarios)")

    with open(timing_out, "w") as f:
        json.dump(timing, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"Wrote {timing_out}")

    no_plan = sum(1 for v in timing.values() if v["result"] == "no_plan")
    solvable = len(timing) - no_plan
    slow = sum(1 for v in timing.values() if v["ms"] > 100)
    print(f"\nSummary: {solvable} solvable, {no_plan} no-plan, {slow} slow (>100ms)")


if __name__ == "__main__":
    main()
