-- GENERATED by cmd/fixturegen — DO NOT EDIT.
-- Source scenarios: lynrummy/conformance/scenarios/*.dsl
-- Regenerate with: go run ./cmd/fixturegen ./lynrummy/conformance/scenarios/*.dsl

module Game.DslConformanceTest exposing (suite)

import Expect
import Game.BoardGeometry exposing (BoardBounds)
import Game.Card exposing (Card, CardValue(..), OriginDeck(..), Suit(..))
import Game.CardStack
    exposing
        ( BoardCard
        , BoardCardState(..)
        , BoardLocation
        , CardStack
        , HandCard
        , HandCardState(..)
        )
import Game.Referee as Referee exposing (RefereeStage(..), refereeStageToString)
import Game.StackType as StackType
import Game.Strategy.Hint as Hint
import Game.Strategy.DirectPlay
import Game.Strategy.HandStacks
import Game.Strategy.LooseCardPlay
import Game.Strategy.PairPeel
import Game.Strategy.PeelForRun
import Game.Strategy.RbSwap
import Game.Strategy.SplitForSet
import Test exposing (Test, describe, test)


standardBounds : BoardBounds
standardBounds =
    { maxWidth = 800, maxHeight = 600, margin = 7 }


-- Invariant check: every stack must classify as a complete group
-- (Set, PureRun, or RedBlackRun). Anything else (Incomplete /
-- Bogus / Dup) means the trick's emission broke the board.
isCleanStack : CardStack -> Bool
isCleanStack s =
    case StackType.getStackType (List.map .card s.boardCards) of
        StackType.Set ->
            True

        StackType.PureRun ->
            True

        StackType.RedBlackRun ->
            True

        _ ->
            False


firstIncompleteStack : List CardStack -> Maybe ( Int, CardStack )
firstIncompleteStack stacks =
    stacks
        |> List.indexedMap Tuple.pair
        |> List.filter (\( _, s ) -> not (isCleanStack s))
        |> List.head



deckIdentityMismatchInRemove : Test
deckIdentityMismatchInRemove =
    test "deck_identity_mismatch_in_remove" <|
        \_ ->
            let
                move =
                    { boardBefore = [ { boardCards = [ { card = { value = Five, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 10, left = 10 } }
                        ]
                    , stacksToRemove = [ { boardCards = [ { card = { value = Five, suit = Heart, originDeck = DeckTwo }, state = FirmlyOnBoard }, { card = { value = Six, suit = Heart, originDeck = DeckTwo }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Heart, originDeck = DeckTwo }, state = FirmlyOnBoard } ], loc = { top = 10, left = 10 } }
                        ]
                    , stacksToAdd = [ { boardCards = [ { card = { value = Five, suit = Heart, originDeck = DeckTwo }, state = FirmlyOnBoard }, { card = { value = Six, suit = Heart, originDeck = DeckTwo }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Heart, originDeck = DeckTwo }, state = FirmlyOnBoard }, { card = { value = Eight, suit = Heart, originDeck = DeckTwo }, state = FreshlyPlayed } ], loc = { top = 10, left = 10 } }
                        ]
                    , handCardsPlayed = [ { card = { value = Eight, suit = Heart, originDeck = DeckTwo }, state = HandNormal } ]
                    }
            in
            case Referee.validateGameMove move standardBounds of
                Ok _ ->
                    Expect.fail ("expected error at stage " ++ "inventory" ++ ", got ok")

                Err err ->
                    if refereeStageToString err.stage /= "inventory" then
                        Expect.fail ("stage: want " ++ "inventory" ++ ", got " ++ refereeStageToString err.stage)
                    else if not (String.contains "not on the board" err.message) then
                        Expect.fail ("message substring " ++ "not on the board" ++ " not found in " ++ err.message)
                    else
                        Expect.pass


geometryCrowded : Test
geometryCrowded =
    test "geometry_crowded" <|
        \_ ->
            let
                move =
                    { boardBefore = []
                    , stacksToRemove = []
                    , stacksToAdd = [ { boardCards = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 10, left = 10 } }
                        , { boardCards = [ { card = { value = Two, suit = Spade, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 10, left = 40 } }
                        ]
                    , handCardsPlayed = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = HandNormal }, { card = { value = Two, suit = Spade, originDeck = DeckOne }, state = HandNormal } ]
                    }
            in
            case Referee.validateGameMove move standardBounds of
                Ok _ ->
                    Expect.fail ("expected error at stage " ++ "geometry" ++ ", got ok")

                Err err ->
                    if refereeStageToString err.stage /= "geometry" then
                        Expect.fail ("stage: want " ++ "geometry" ++ ", got " ++ refereeStageToString err.stage)
                    else if not (String.contains "too close" err.message) then
                        Expect.fail ("message substring " ++ "too close" ++ " not found in " ++ err.message)
                    else
                        Expect.pass


geometryOutOfBounds : Test
geometryOutOfBounds =
    test "geometry_out_of_bounds" <|
        \_ ->
            let
                move =
                    { boardBefore = []
                    , stacksToRemove = []
                    , stacksToAdd = [ { boardCards = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 10, left = 790 } }
                        ]
                    , handCardsPlayed = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = HandNormal } ]
                    }
            in
            case Referee.validateGameMove move standardBounds of
                Ok _ ->
                    Expect.fail ("expected error at stage " ++ "geometry" ++ ", got ok")

                Err err ->
                    if refereeStageToString err.stage /= "geometry" then
                        Expect.fail ("stage: want " ++ "geometry" ++ ", got " ++ refereeStageToString err.stage)
                    else if not (String.contains "outside" err.message) then
                        Expect.fail ("message substring " ++ "outside" ++ " not found in " ++ err.message)
                    else
                        Expect.pass


geometryOverlap : Test
geometryOverlap =
    test "geometry_overlap" <|
        \_ ->
            let
                move =
                    { boardBefore = []
                    , stacksToRemove = []
                    , stacksToAdd = [ { boardCards = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 10, left = 10 } }
                        , { boardCards = [ { card = { value = Two, suit = Spade, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 10, left = 10 } }
                        ]
                    , handCardsPlayed = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = HandNormal }, { card = { value = Two, suit = Spade, originDeck = DeckOne }, state = HandNormal } ]
                    }
            in
            case Referee.validateGameMove move standardBounds of
                Ok _ ->
                    Expect.fail ("expected error at stage " ++ "geometry" ++ ", got ok")

                Err err ->
                    if refereeStageToString err.stage /= "geometry" then
                        Expect.fail ("stage: want " ++ "geometry" ++ ", got " ++ refereeStageToString err.stage)
                    else if not (String.contains "overlap" err.message) then
                        Expect.fail ("message substring " ++ "overlap" ++ " not found in " ++ err.message)
                    else
                        Expect.pass


hintDirectPlayWinsPriorityOnOpeningBoard : Test
hintDirectPlayWinsPriorityOnOpeningBoard =
    test "hint_direct_play_wins_priority_on_opening_board" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Seven, suit = Heart, originDeck = DeckTwo }, state = HandNormal } ]

                hand =
                    { handCards = handCards }

                board =
                    [ { boardCards = [ { card = { value = King, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Ace, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Two, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 70, left = 20 } }
                        , { boardCards = [ { card = { value = Ten, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Jack, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Queen, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = King, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 160, left = 80 } }
                        , { boardCards = [ { card = { value = Two, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Four, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 100, left = 140 } }
                        , { boardCards = [ { card = { value = Seven, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 200 } }
                        , { boardCards = [ { card = { value = Ace, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Ace, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 130, left = 260 } }
                        , { boardCards = [ { card = { value = Two, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Four, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Five, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 70, left = 320 } }
                        ]

                got =
                    Hint.buildSuggestions hand board
            in
            if List.length got /= 1 then
                Expect.fail ("suggestion count: want 1, got " ++ String.fromInt (List.length got))

            else
                let
                    want0 =
                        { trickId = "direct_play", handCards = [ { value = Seven, suit = Heart, originDeck = DeckTwo } ] }

                in
                Expect.all
                    [ \_ -> List.drop 0 got |> List.head |> Maybe.map (\s -> { trickId = s.trickId, handCards = s.handCards }) |> Expect.equal (Just want0)
                    ]
                    ()


hintEmptyHandNoSuggestions : Test
hintEmptyHandNoSuggestions =
    test "hint_empty_hand_no_suggestions" <|
        \_ ->
            let
                handCards =
                    []

                hand =
                    { handCards = handCards }

                board =
                    [ { boardCards = [ { card = { value = King, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Ace, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Two, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 70, left = 20 } }
                        , { boardCards = [ { card = { value = Ten, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Jack, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Queen, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = King, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 160, left = 80 } }
                        , { boardCards = [ { card = { value = Two, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Four, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 100, left = 140 } }
                        ]

                got =
                    Hint.buildSuggestions hand board
            in
            if List.length got /= 0 then
                Expect.fail ("suggestion count: want 0, got " ++ String.fromInt (List.length got))

            else
                Expect.pass


hintInvariantDirectPlayCompleteSet : Test
hintInvariantDirectPlayCompleteSet =
    test "hint_invariant_direct_play_complete_set" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Five, suit = Diamond, originDeck = DeckTwo }, state = HandNormal } ]

                board =
                    [ { boardCards = [ { card = { value = Five, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Five, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Five, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 40 } }
                        ]

                plays =
                    Game.Strategy.DirectPlay.trick.findPlays handCards board
            in
            case plays of
                [] ->
                    Expect.fail "trick did not fire (no plays)"

                play :: _ ->
                    let
                        ( afterBoard, _ ) =
                            play.apply board
                    in
                    case firstIncompleteStack afterBoard of
                        Nothing ->
                            Expect.pass

                        Just ( i, s ) ->
                            Expect.fail
                                ("stack "
                                    ++ String.fromInt i
                                    ++ " is incomplete after trick emission: "
                                    ++ Debug.toString s
                                )


hintInvariantDirectPlayExtendPureRun : Test
hintInvariantDirectPlayExtendPureRun =
    test "hint_invariant_direct_play_extend_pure_run" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Nine, suit = Diamond, originDeck = DeckTwo }, state = HandNormal } ]

                board =
                    [ { boardCards = [ { card = { value = Six, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Eight, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 40 } }
                        , { boardCards = [ { card = { value = Ace, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Two, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 180, left = 40 } }
                        ]

                plays =
                    Game.Strategy.DirectPlay.trick.findPlays handCards board
            in
            case plays of
                [] ->
                    Expect.fail "trick did not fire (no plays)"

                play :: _ ->
                    let
                        ( afterBoard, _ ) =
                            play.apply board
                    in
                    case firstIncompleteStack afterBoard of
                        Nothing ->
                            Expect.pass

                        Just ( i, s ) ->
                            Expect.fail
                                ("stack "
                                    ++ String.fromInt i
                                    ++ " is incomplete after trick emission: "
                                    ++ Debug.toString s
                                )


hintInvariantHandStacksPureRunReversedHand : Test
hintInvariantHandStacksPureRunReversedHand =
    test "hint_invariant_hand_stacks_pure_run_reversed_hand" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Seven, suit = Heart, originDeck = DeckTwo }, state = HandNormal }, { card = { value = Six, suit = Heart, originDeck = DeckTwo }, state = HandNormal }, { card = { value = Five, suit = Heart, originDeck = DeckTwo }, state = HandNormal } ]

                board =
                    [ { boardCards = [ { card = { value = Jack, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Queen, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = King, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 40 } }
                        ]

                plays =
                    Game.Strategy.HandStacks.trick.findPlays handCards board
            in
            case plays of
                [] ->
                    Expect.fail "trick did not fire (no plays)"

                play :: _ ->
                    let
                        ( afterBoard, _ ) =
                            play.apply board
                    in
                    case firstIncompleteStack afterBoard of
                        Nothing ->
                            Expect.pass

                        Just ( i, s ) ->
                            Expect.fail
                                ("stack "
                                    ++ String.fromInt i
                                    ++ " is incomplete after trick emission: "
                                    ++ Debug.toString s
                                )


hintInvariantHandStacksPureRunThreeCard : Test
hintInvariantHandStacksPureRunThreeCard =
    test "hint_invariant_hand_stacks_pure_run_three_card" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Five, suit = Heart, originDeck = DeckTwo }, state = HandNormal }, { card = { value = Six, suit = Heart, originDeck = DeckTwo }, state = HandNormal }, { card = { value = Seven, suit = Heart, originDeck = DeckTwo }, state = HandNormal } ]

                board =
                    [ { boardCards = [ { card = { value = Jack, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Queen, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = King, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 40 } }
                        ]

                plays =
                    Game.Strategy.HandStacks.trick.findPlays handCards board
            in
            case plays of
                [] ->
                    Expect.fail "trick did not fire (no plays)"

                play :: _ ->
                    let
                        ( afterBoard, _ ) =
                            play.apply board
                    in
                    case firstIncompleteStack afterBoard of
                        Nothing ->
                            Expect.pass

                        Just ( i, s ) ->
                            Expect.fail
                                ("stack "
                                    ++ String.fromInt i
                                    ++ " is incomplete after trick emission: "
                                    ++ Debug.toString s
                                )


hintInvariantHandStacksRbRunThreeCard : Test
hintInvariantHandStacksRbRunThreeCard =
    test "hint_invariant_hand_stacks_rb_run_three_card" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Five, suit = Heart, originDeck = DeckTwo }, state = HandNormal }, { card = { value = Six, suit = Club, originDeck = DeckTwo }, state = HandNormal }, { card = { value = Seven, suit = Heart, originDeck = DeckTwo }, state = HandNormal } ]

                board =
                    [ { boardCards = [ { card = { value = Jack, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Queen, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = King, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 40 } }
                        ]

                plays =
                    Game.Strategy.HandStacks.trick.findPlays handCards board
            in
            case plays of
                [] ->
                    Expect.fail "trick did not fire (no plays)"

                play :: _ ->
                    let
                        ( afterBoard, _ ) =
                            play.apply board
                    in
                    case firstIncompleteStack afterBoard of
                        Nothing ->
                            Expect.pass

                        Just ( i, s ) ->
                            Expect.fail
                                ("stack "
                                    ++ String.fromInt i
                                    ++ " is incomplete after trick emission: "
                                    ++ Debug.toString s
                                )


hintInvariantHandStacksSetThreeOfAKind : Test
hintInvariantHandStacksSetThreeOfAKind =
    test "hint_invariant_hand_stacks_set_three_of_a_kind" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Four, suit = Heart, originDeck = DeckTwo }, state = HandNormal }, { card = { value = Four, suit = Spade, originDeck = DeckTwo }, state = HandNormal }, { card = { value = Four, suit = Diamond, originDeck = DeckTwo }, state = HandNormal } ]

                board =
                    [ { boardCards = [ { card = { value = Jack, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Queen, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = King, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 40 } }
                        ]

                plays =
                    Game.Strategy.HandStacks.trick.findPlays handCards board
            in
            case plays of
                [] ->
                    Expect.fail "trick did not fire (no plays)"

                play :: _ ->
                    let
                        ( afterBoard, _ ) =
                            play.apply board
                    in
                    case firstIncompleteStack afterBoard of
                        Nothing ->
                            Expect.pass

                        Just ( i, s ) ->
                            Expect.fail
                                ("stack "
                                    ++ String.fromInt i
                                    ++ " is incomplete after trick emission: "
                                    ++ Debug.toString s
                                )


hintInvariantLooseCardPlayPeelSetToRun : Test
hintInvariantLooseCardPlayPeelSetToRun =
    test "hint_invariant_loose_card_play_peel_set_to_run" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Three, suit = Club, originDeck = DeckTwo }, state = HandNormal } ]

                board =
                    [ { boardCards = [ { card = { value = Four, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Four, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Four, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Four, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 40 } }
                        , { boardCards = [ { card = { value = Five, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 300 } }
                        ]

                plays =
                    Game.Strategy.LooseCardPlay.trick.findPlays handCards board
            in
            case plays of
                [] ->
                    Expect.fail "trick did not fire (no plays)"

                play :: _ ->
                    let
                        ( afterBoard, _ ) =
                            play.apply board
                    in
                    case firstIncompleteStack afterBoard of
                        Nothing ->
                            Expect.pass

                        Just ( i, s ) ->
                            Expect.fail
                                ("stack "
                                    ++ String.fromInt i
                                    ++ " is incomplete after trick emission: "
                                    ++ Debug.toString s
                                )


hintInvariantPairPeelRunPairPureEdge : Test
hintInvariantPairPeelRunPairPureEdge =
    test "hint_invariant_pair_peel_run_pair_pure_edge" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Five, suit = Heart, originDeck = DeckTwo }, state = HandNormal }, { card = { value = Six, suit = Heart, originDeck = DeckTwo }, state = HandNormal } ]

                board =
                    [ { boardCards = [ { card = { value = Seven, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Eight, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Nine, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Ten, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 40 } }
                        ]

                plays =
                    Game.Strategy.PairPeel.trick.findPlays handCards board
            in
            case plays of
                [] ->
                    Expect.fail "trick did not fire (no plays)"

                play :: _ ->
                    let
                        ( afterBoard, _ ) =
                            play.apply board
                    in
                    case firstIncompleteStack afterBoard of
                        Nothing ->
                            Expect.pass

                        Just ( i, s ) ->
                            Expect.fail
                                ("stack "
                                    ++ String.fromInt i
                                    ++ " is incomplete after trick emission: "
                                    ++ Debug.toString s
                                )


hintInvariantPairPeelRunPairReversedHand : Test
hintInvariantPairPeelRunPairReversedHand =
    test "hint_invariant_pair_peel_run_pair_reversed_hand" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Six, suit = Heart, originDeck = DeckTwo }, state = HandNormal }, { card = { value = Five, suit = Heart, originDeck = DeckTwo }, state = HandNormal } ]

                board =
                    [ { boardCards = [ { card = { value = Seven, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Eight, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Nine, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Ten, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 40 } }
                        ]

                plays =
                    Game.Strategy.PairPeel.trick.findPlays handCards board
            in
            case plays of
                [] ->
                    Expect.fail "trick did not fire (no plays)"

                play :: _ ->
                    let
                        ( afterBoard, _ ) =
                            play.apply board
                    in
                    case firstIncompleteStack afterBoard of
                        Nothing ->
                            Expect.pass

                        Just ( i, s ) ->
                            Expect.fail
                                ("stack "
                                    ++ String.fromInt i
                                    ++ " is incomplete after trick emission: "
                                    ++ Debug.toString s
                                )


hintInvariantPairPeelSetPairEdge : Test
hintInvariantPairPeelSetPairEdge =
    test "hint_invariant_pair_peel_set_pair_edge" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Five, suit = Heart, originDeck = DeckTwo }, state = HandNormal }, { card = { value = Five, suit = Spade, originDeck = DeckTwo }, state = HandNormal } ]

                board =
                    [ { boardCards = [ { card = { value = Five, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Eight, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 40 } }
                        ]

                plays =
                    Game.Strategy.PairPeel.trick.findPlays handCards board
            in
            case plays of
                [] ->
                    Expect.fail "trick did not fire (no plays)"

                play :: _ ->
                    let
                        ( afterBoard, _ ) =
                            play.apply board
                    in
                    case firstIncompleteStack afterBoard of
                        Nothing ->
                            Expect.pass

                        Just ( i, s ) ->
                            Expect.fail
                                ("stack "
                                    ++ String.fromInt i
                                    ++ " is incomplete after trick emission: "
                                    ++ Debug.toString s
                                )


hintInvariantPairPeelSetPairMiddle : Test
hintInvariantPairPeelSetPairMiddle =
    test "hint_invariant_pair_peel_set_pair_middle" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Five, suit = Heart, originDeck = DeckTwo }, state = HandNormal }, { card = { value = Five, suit = Spade, originDeck = DeckTwo }, state = HandNormal } ]

                board =
                    [ { boardCards = [ { card = { value = Two, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Four, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Five, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Eight, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Nine, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 40 } }
                        ]

                plays =
                    Game.Strategy.PairPeel.trick.findPlays handCards board
            in
            case plays of
                [] ->
                    Expect.fail "trick did not fire (no plays)"

                play :: _ ->
                    let
                        ( afterBoard, _ ) =
                            play.apply board
                    in
                    case firstIncompleteStack afterBoard of
                        Nothing ->
                            Expect.pass

                        Just ( i, s ) ->
                            Expect.fail
                                ("stack "
                                    ++ String.fromInt i
                                    ++ " is incomplete after trick emission: "
                                    ++ Debug.toString s
                                )


hintInvariantPeelForRunRbEdges : Test
hintInvariantPeelForRunRbEdges =
    test "hint_invariant_peel_for_run_rb_edges" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Ten, suit = Diamond, originDeck = DeckTwo }, state = HandNormal } ]

                board =
                    [ { boardCards = [ { card = { value = Six, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Eight, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Nine, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 40 } }
                        , { boardCards = [ { card = { value = Jack, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Queen, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = King, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Ace, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 300 } }
                        ]

                plays =
                    Game.Strategy.PeelForRun.trick.findPlays handCards board
            in
            case plays of
                [] ->
                    Expect.fail "trick did not fire (no plays)"

                play :: _ ->
                    let
                        ( afterBoard, _ ) =
                            play.apply board
                    in
                    case firstIncompleteStack afterBoard of
                        Nothing ->
                            Expect.pass

                        Just ( i, s ) ->
                            Expect.fail
                                ("stack "
                                    ++ String.fromInt i
                                    ++ " is incomplete after trick emission: "
                                    ++ Debug.toString s
                                )


hintInvariantRbSwapMiddleSwapClubsHome : Test
hintInvariantRbSwapMiddleSwapClubsHome =
    test "hint_invariant_rb_swap_middle_swap_clubs_home" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Four, suit = Spade, originDeck = DeckTwo }, state = HandNormal } ]

                board =
                    [ { boardCards = [ { card = { value = Three, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Four, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Five, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 40 } }
                        , { boardCards = [ { card = { value = Ace, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Two, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 300 } }
                        , { boardCards = [ { card = { value = Nine, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Ten, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Jack, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 180, left = 40 } }
                        ]

                plays =
                    Game.Strategy.RbSwap.trick.findPlays handCards board
            in
            case plays of
                [] ->
                    Expect.fail "trick did not fire (no plays)"

                play :: _ ->
                    let
                        ( afterBoard, _ ) =
                            play.apply board
                    in
                    case firstIncompleteStack afterBoard of
                        Nothing ->
                            Expect.pass

                        Just ( i, s ) ->
                            Expect.fail
                                ("stack "
                                    ++ String.fromInt i
                                    ++ " is incomplete after trick emission: "
                                    ++ Debug.toString s
                                )


hintInvariantSplitForSetBothEdges : Test
hintInvariantSplitForSetBothEdges =
    test "hint_invariant_split_for_set_both_edges" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Five, suit = Heart, originDeck = DeckTwo }, state = HandNormal } ]

                board =
                    [ { boardCards = [ { card = { value = Five, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Eight, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 40 } }
                        , { boardCards = [ { card = { value = Five, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Eight, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 300 } }
                        ]

                plays =
                    Game.Strategy.SplitForSet.trick.findPlays handCards board
            in
            case plays of
                [] ->
                    Expect.fail "trick did not fire (no plays)"

                play :: _ ->
                    let
                        ( afterBoard, _ ) =
                            play.apply board
                    in
                    case firstIncompleteStack afterBoard of
                        Nothing ->
                            Expect.pass

                        Just ( i, s ) ->
                            Expect.fail
                                ("stack "
                                    ++ String.fromInt i
                                    ++ " is incomplete after trick emission: "
                                    ++ Debug.toString s
                                )


hintInvariantSplitForSetOneMiddleOneEdge : Test
hintInvariantSplitForSetOneMiddleOneEdge =
    test "hint_invariant_split_for_set_one_middle_one_edge" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Five, suit = Heart, originDeck = DeckTwo }, state = HandNormal } ]

                board =
                    [ { boardCards = [ { card = { value = Two, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Four, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Five, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Eight, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Nine, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 40 } }
                        , { boardCards = [ { card = { value = Five, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Eight, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 400 } }
                        ]

                plays =
                    Game.Strategy.SplitForSet.trick.findPlays handCards board
            in
            case plays of
                [] ->
                    Expect.fail "trick did not fire (no plays)"

                play :: _ ->
                    let
                        ( afterBoard, _ ) =
                            play.apply board
                    in
                    case firstIncompleteStack afterBoard of
                        Nothing ->
                            Expect.pass

                        Just ( i, s ) ->
                            Expect.fail
                                ("stack "
                                    ++ String.fromInt i
                                    ++ " is incomplete after trick emission: "
                                    ++ Debug.toString s
                                )


hintNoPlaysForLonelyUnplayableCard : Test
hintNoPlaysForLonelyUnplayableCard =
    test "hint_no_plays_for_lonely_unplayable_card" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Nine, suit = Spade, originDeck = DeckOne }, state = HandNormal } ]

                hand =
                    { handCards = handCards }

                board =
                    [ { boardCards = [ { card = { value = Two, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Four, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 70, left = 20 } }
                        ]

                got =
                    Hint.buildSuggestions hand board
            in
            if List.length got /= 0 then
                Expect.fail ("suggestion count: want 0, got " ++ String.fromInt (List.length got))

            else
                Expect.pass


identityReorderBreaksMatch : Test
identityReorderBreaksMatch =
    test "identity_reorder_breaks_match" <|
        \_ ->
            let
                move =
                    { boardBefore = [ { boardCards = [ { card = { value = Five, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Five, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Five, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 100, left = 100 } }
                        ]
                    , stacksToRemove = [ { boardCards = [ { card = { value = Five, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Five, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Five, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 100, left = 100 } }
                        ]
                    , stacksToAdd = [ { boardCards = [ { card = { value = Five, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Five, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Five, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Five, suit = Diamond, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 100, left = 100 } }
                        ]
                    , handCardsPlayed = [ { card = { value = Five, suit = Diamond, originDeck = DeckOne }, state = HandNormal } ]
                    }
            in
            case Referee.validateGameMove move standardBounds of
                Ok _ ->
                    Expect.fail ("expected error at stage " ++ "inventory" ++ ", got ok")

                Err err ->
                    if refereeStageToString err.stage /= "inventory" then
                        Expect.fail ("stage: want " ++ "inventory" ++ ", got " ++ refereeStageToString err.stage)
                    else if not (String.contains "not on the board" err.message) then
                        Expect.fail ("message substring " ++ "not on the board" ++ " not found in " ++ err.message)
                    else
                        Expect.pass


inventoryCardFromNowhere : Test
inventoryCardFromNowhere =
    test "inventory_card_from_nowhere" <|
        \_ ->
            let
                move =
                    { boardBefore = []
                    , stacksToRemove = []
                    , stacksToAdd = [ { boardCards = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = FreshlyPlayed }, { card = { value = Two, suit = Heart, originDeck = DeckOne }, state = FreshlyPlayed }, { card = { value = Three, suit = Heart, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 10, left = 10 } }
                        ]
                    , handCardsPlayed = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = HandNormal }, { card = { value = Two, suit = Heart, originDeck = DeckOne }, state = HandNormal } ]
                    }
            in
            case Referee.validateGameMove move standardBounds of
                Ok _ ->
                    Expect.fail ("expected error at stage " ++ "inventory" ++ ", got ok")

                Err err ->
                    if refereeStageToString err.stage /= "inventory" then
                        Expect.fail ("stage: want " ++ "inventory" ++ ", got " ++ refereeStageToString err.stage)
                    else if not (String.contains "no source" err.message) then
                        Expect.fail ("message substring " ++ "no source" ++ " not found in " ++ err.message)
                    else
                        Expect.pass


midturnAllowsBogus : Test
midturnAllowsBogus =
    test "midturn_allows_bogus" <|
        \_ ->
            let
                move =
                    { boardBefore = []
                    , stacksToRemove = []
                    , stacksToAdd = [ { boardCards = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = FreshlyPlayed }, { card = { value = Five, suit = Club, originDeck = DeckOne }, state = FreshlyPlayed }, { card = { value = King, suit = Diamond, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 10, left = 10 } }
                        ]
                    , handCardsPlayed = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = HandNormal }, { card = { value = Five, suit = Club, originDeck = DeckOne }, state = HandNormal }, { card = { value = King, suit = Diamond, originDeck = DeckOne }, state = HandNormal } ]
                    }
            in
            case Referee.validateGameMove move standardBounds of
                Ok _ ->
                    Expect.pass

                Err err ->
                    Expect.fail (refereeStageToString err.stage ++ ": " ++ err.message)


turnCompleteCleanBoard : Test
turnCompleteCleanBoard =
    test "turn_complete_clean_board" <|
        \_ ->
            let
                board =
                    [ { boardCards = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Two, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 10, left = 10 } }
                    , { boardCards = [ { card = { value = King, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = King, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = King, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 10, left = 200 } }
                    ]
            in
            case Referee.validateTurnComplete board standardBounds of
                Ok _ ->
                    Expect.pass

                Err err ->
                    Expect.fail (refereeStageToString err.stage ++ ": " ++ err.message)


turnCompleteRejectsIncomplete : Test
turnCompleteRejectsIncomplete =
    test "turn_complete_rejects_incomplete" <|
        \_ ->
            let
                board =
                    [ { boardCards = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Two, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 10, left = 10 } }
                    ]
            in
            case Referee.validateTurnComplete board standardBounds of
                Ok _ ->
                    Expect.fail ("expected error at stage " ++ "semantics" ++ ", got ok")

                Err err ->
                    if refereeStageToString err.stage /= "semantics" then
                        Expect.fail ("stage: want " ++ "semantics" ++ ", got " ++ refereeStageToString err.stage)
                    else if not (String.contains "incomplete" err.message) then
                        Expect.fail ("message substring " ++ "incomplete" ++ " not found in " ++ err.message)
                    else
                        Expect.pass


validExtendRunWith8H : Test
validExtendRunWith8H =
    test "valid_extend_run_with_8H" <|
        \_ ->
            let
                move =
                    { boardBefore = [ { boardCards = [ { card = { value = Five, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 10, left = 10 } }
                        ]
                    , stacksToRemove = [ { boardCards = [ { card = { value = Five, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 10, left = 10 } }
                        ]
                    , stacksToAdd = [ { boardCards = [ { card = { value = Five, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Eight, suit = Heart, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 10, left = 10 } }
                        ]
                    , handCardsPlayed = [ { card = { value = Eight, suit = Heart, originDeck = DeckOne }, state = HandNormal } ]
                    }
            in
            case Referee.validateGameMove move standardBounds of
                Ok _ ->
                    Expect.pass

                Err err ->
                    Expect.fail (refereeStageToString err.stage ++ ": " ++ err.message)


suite : Test
suite =
    describe "DSL conformance"
        [ deckIdentityMismatchInRemove
        , geometryCrowded
        , geometryOutOfBounds
        , geometryOverlap
        , hintDirectPlayWinsPriorityOnOpeningBoard
        , hintEmptyHandNoSuggestions
        , hintInvariantDirectPlayCompleteSet
        , hintInvariantDirectPlayExtendPureRun
        , hintInvariantHandStacksPureRunReversedHand
        , hintInvariantHandStacksPureRunThreeCard
        , hintInvariantHandStacksRbRunThreeCard
        , hintInvariantHandStacksSetThreeOfAKind
        , hintInvariantLooseCardPlayPeelSetToRun
        , hintInvariantPairPeelRunPairPureEdge
        , hintInvariantPairPeelRunPairReversedHand
        , hintInvariantPairPeelSetPairEdge
        , hintInvariantPairPeelSetPairMiddle
        , hintInvariantPeelForRunRbEdges
        , hintInvariantRbSwapMiddleSwapClubsHome
        , hintInvariantSplitForSetBothEdges
        , hintInvariantSplitForSetOneMiddleOneEdge
        , hintNoPlaysForLonelyUnplayableCard
        , identityReorderBreaksMatch
        , inventoryCardFromNowhere
        , midturnAllowsBogus
        , turnCompleteCleanBoard
        , turnCompleteRejectsIncomplete
        , validExtendRunWith8H
        ]
