// replay_puzzles.ts — emit conformance-ready DSL for every puzzle
// in games/lynrummy/puzzles/puzzles.json.
//
// For each puzzle:
//   1. Decode the initial board.
//   2. Partition stacks into helper / trouble (same boundary the
//      solver uses).
//   3. Run `solveStateWithDescs` and capture the resulting plan
//      lines verbatim.
//   4. Emit a `scenario puzzle_<name>` block in the existing
//      `op: solve` DSL shape (the one `planner_mined.dsl` uses).
//
// The output is the contract: pipe it to
// `games/lynrummy/conformance/scenarios/planner_puzzles.dsl` and
// fixturegen turns each puzzle into a regression test
// automatically. If the solver's output for a puzzle later
// changes, the conformance gate fails — the operator inspects
// the diff, decides whether the new plan is better (re-run +
// commit) or a regression (fix the solver), and the captured
// DSL stays in lockstep with the spec.
//
// Usage:
//   node tools/replay_puzzles.ts > <output.dsl>
//
// No flags: stdout always; the redirect is your choice.

import * as fs from "node:fs";
import * as path from "node:path";

import type { Card } from "../src/rules/card.ts";
import { cardLabel } from "../src/rules/card.ts";
import type { BoardStack } from "../src/geometry.ts";
import { solveStateWithDescs } from "../src/engine_v2.ts";
import {
  classifyStack,
  KIND_RUN, KIND_RB, KIND_SET,
} from "../src/classified_card_stack.ts";

// --- Puzzle JSON shape -----------------------------------------------

interface JsonCard { value: number; suit: number; origin_deck: number }
interface JsonBoardCard { card: JsonCard; state: number }
interface JsonLoc { top: number; left: number }
interface JsonStack { board_cards: JsonBoardCard[]; loc: JsonLoc }
interface JsonInitialState { board: JsonStack[] }
interface JsonPuzzle { name: string; title: string; initial_state: JsonInitialState }
interface JsonCatalog { puzzles: JsonPuzzle[] }

function decodeBoard(stacks: JsonStack[]): BoardStack[] {
  return stacks.map(s => ({
    cards: s.board_cards.map(bc => [bc.card.value, bc.card.suit, bc.card.origin_deck] as Card),
    loc: { top: s.loc.top, left: s.loc.left },
  }));
}

// --- Bucket partition (mirror of engine_entry.solveBoard) -----------

interface Buckets {
  helper: Card[][];
  trouble: Card[][];
}

function partitionBoard(board: readonly BoardStack[]): Buckets {
  const helper: Card[][] = [];
  const trouble: Card[][] = [];
  for (const stack of board) {
    const ccs = classifyStack(stack.cards);
    const cards = stack.cards as Card[];
    if (ccs !== null && (ccs.kind === KIND_RUN || ccs.kind === KIND_RB || ccs.kind === KIND_SET)) {
      helper.push(cards);
    } else {
      trouble.push(cards);
    }
  }
  return { helper, trouble };
}

// --- DSL emit --------------------------------------------------------
//
// Matches the `op: solve` shape used by planner_mined.dsl: each
// scenario carries helper/trouble blocks (no growing/complete since
// puzzles always start with empty growing+complete) and an
// `expect.plan_lines:` list of plan-line strings, verbatim from
// the engine. Stack-card labels use the engine's native cardLabel
// (`:1` deck suffix); the parser accepts that form alongside the
// `'` form planner_mined.dsl happens to use.
//
// Locs are pinned to (0,0) — solver doesn't consult geometry, the
// existing planner DSLs do the same.

function dslStack(cards: readonly Card[]): string {
  return cards.map(cardLabel).join(" ");
}

/** Escape a plan-line for embedding in a DSL double-quoted string.
 *  The plan-line strings the engine emits are built from
 *  `cardLabel` + a small fixed alphabet; the only characters that
 *  matter are `"` and `\`. We don't need to JSON-escape the unicode
 *  arrow — the DSL parser passes it through. */
function dslQuote(s: string): string {
  return '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}

function emitPuzzle(p: JsonPuzzle): void {
  const board = decodeBoard(p.initial_state.board);
  const { helper, trouble } = partitionBoard(board);
  const plan = solveStateWithDescs({
    helper, trouble, growing: [], complete: [],
  });

  const lines: string[] = [];
  lines.push(`scenario puzzle_${p.name}`);
  lines.push(`  desc: Replay of ${p.title}. Auto-generated by tools/replay_puzzles.ts.`);
  lines.push(`  op: solve`);
  lines.push(`  helper:`);
  for (const stack of helper) {
    lines.push(`    at (0,0): ${dslStack(stack)}`);
  }
  lines.push(`  trouble:`);
  for (const stack of trouble) {
    lines.push(`    at (0,0): ${dslStack(stack)}`);
  }
  lines.push(`  expect:`);
  if (plan === null) {
    // No plan within budget. The existing solve DSL doesn't
    // model "no plan" directly — emit an empty plan_lines list
    // and a comment so the operator notices.
    lines.push(`    # solver returned NULL (no plan within budget)`);
    lines.push(`    plan_lines:`);
  } else {
    lines.push(`    plan_lines:`);
    for (const planLine of plan) {
      lines.push(`      - ${dslQuote(planLine.line)}`);
    }
  }
  process.stdout.write(lines.join("\n") + "\n\n");
}

// --- Entry point -----------------------------------------------------

function main(): void {
  const here = path.dirname(new URL(import.meta.url).pathname);
  const catalogPath = path.resolve(here, "../../puzzles/puzzles.json");
  const raw = fs.readFileSync(catalogPath, "utf8");
  const catalog: JsonCatalog = JSON.parse(raw);

  process.stdout.write(
    "# AUTO-GENERATED by tools/replay_puzzles.ts.\n" +
    "# Do NOT hand-edit. Re-run the exporter to refresh.\n" +
    "#\n" +
    "# Each scenario captures the canonical TS solver's plan for\n" +
    "# one entry in games/lynrummy/puzzles/puzzles.json. The plan\n" +
    "# you see is the plan the engine produces RIGHT NOW for that\n" +
    "# board — when reading, treat \"expected\" as a snapshot of\n" +
    "# \"actual\". Drift between this file and the engine surfaces\n" +
    "# at the conformance gate; regenerate to update the spec.\n" +
    "\n",
  );

  for (const p of catalog.puzzles) {
    emitPuzzle(p);
  }
}

main();
