// Puzzles — a standalone Elm app that hosts a vertical list
// of curated LynRummy puzzles. Always within-a-turn: no dealer,
// no deck, no turn cycling.
//
// Go surface: serve the page (HTML chrome + bootstrap script),
// serve the compiled puzzles.js, serve the puzzle catalog JSON
// alongside a freshly-allocated page-load session id. Actions
// and annotations now post to the unified
// /gopher/lynrummy-elm/sessions/<id>/... endpoints (Go is dumb
// file storage; Elm carries puzzle_name in the body when needed).

package views

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"
)

// PuzzlesJSPath — the Puzzles app's compiled JS lives alongside
// the Main app's elm.js since the unification 2026-04-27. Both
// entry points (Main.elm, Puzzles.elm) compile into the same
// games/lynrummy/elm/ directory.
var PuzzlesJSPath = "games/lynrummy/elm/puzzles.js"

// PuzzlesCatalogPath — the catalog JSON the Puzzles gallery
// loads. Generated by games/lynrummy/python/puzzle_catalog.py.
var PuzzlesCatalogPath = "games/lynrummy/puzzles/puzzles.json"

// HandlePuzzles dispatches /gopher/puzzles/*. Puzzle actions
// now write to the unified /gopher/lynrummy-elm/sessions/<id>/
// actions/<seq> URL space alongside full-game actions. The
// /gopher/puzzles/annotate route survives as a back-compat
// shim (Puzzles.elm still POSTs there); short-lived.
func HandlePuzzles(w http.ResponseWriter, r *http.Request) {
	sub := strings.TrimPrefix(r.URL.Path, "/gopher/puzzles")
	sub = strings.TrimPrefix(sub, "/")
	switch sub {
	case "", "/":
		puzzlesPage(w)
	case "puzzles.js":
		puzzlesJS(w)
	case "catalog":
		puzzlesCatalog(w)
	case "annotate":
		puzzlesAnnotateShim(w, r)
	default:
		http.NotFound(w, r)
	}
}

// puzzlesAnnotateShim handles POST /gopher/puzzles/annotate
// with body {session_id, puzzle_name, user_name, body}. Writes
// the body verbatim to a new annotations/<n>.json file under
// the session dir.
func puzzlesAnnotateShim(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	body, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, "read body: "+err.Error(), http.StatusBadRequest)
		return
	}
	var probe struct {
		SessionID int64 `json:"session_id"`
	}
	if err := json.Unmarshal(body, &probe); err != nil || probe.SessionID <= 0 {
		http.Error(w, "decode body / missing session_id", http.StatusBadRequest)
		return
	}
	if !SessionExists(probe.SessionID) {
		http.NotFound(w, r)
		return
	}
	files, _ := ListAnnotationFiles(probe.SessionID)
	nextSeq := int64(len(files) + 1)
	rel := "annotations/" + strconv.FormatInt(nextSeq, 10) + ".json"
	if err := WriteSessionFile(probe.SessionID, rel, body); err != nil {
		http.Error(w, "write: "+err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Write([]byte(`{"ok":true}`))
}

func puzzlesPage(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprint(w, `<!doctype html>
<html><head><meta charset="utf-8"><title>Puzzles</title>
<style>
  body { margin: 0; font-family: sans-serif; background: #f4f4ec; }
  .app-nav { padding: 8px 16px; background: #000080; color: white; font-size: 13px; }
  .app-nav a { color: white; text-decoration: none; margin-right: 14px; }
  .app-nav a:hover { text-decoration: underline; }
</style>
</head><body>
<div class="app-nav">
  <a href="/gopher/">← Gopher home</a>
  <a href="/gopher/game-lobby">Game lobby</a>
  <a href="/gopher/lynrummy-elm/">Play LynRummy</a>
  <a href="/gopher/puzzles/">Puzzles</a>
</div>
<div id="root"></div>
<script src="/gopher/puzzles/puzzles.js"></script>
<script>
  Elm.Puzzles.init({ node: document.getElementById("root") });
</script>
</body></html>`)
}

func puzzlesJS(w http.ResponseWriter) {
	data, err := os.ReadFile(PuzzlesJSPath)
	if err != nil {
		http.Error(w, "puzzles.js not found — run `elm make src/Puzzles.elm --output=puzzles.js` in games/lynrummy/elm/", http.StatusNotFound)
		return
	}
	w.Header().Set("Content-Type", "application/javascript; charset=utf-8")
	w.Write(data)
}

// puzzlesCatalog serves the Python-generated puzzle catalog
// alongside a freshly allocated page-load session id. The
// catalog JSON on disk is `{"puzzles": [...]}`. We allocate a
// session (the one smart exception in our otherwise-dumb
// surface) and write a meta.json so the session dir is real;
// the response merges session_id into the catalog payload.
func puzzlesCatalog(w http.ResponseWriter) {
	catalogJSON, err := os.ReadFile(PuzzlesCatalogPath)
	if err != nil {
		http.Error(w, "puzzles.json not found — run "+
			"`python3 games/lynrummy/python/puzzle_catalog.py`",
			http.StatusNotFound)
		return
	}

	var catalog struct {
		Puzzles []json.RawMessage `json:"puzzles"`
	}
	if err := json.Unmarshal(catalogJSON, &catalog); err != nil {
		log.Printf("puzzles catalog: catalog decode err=%v", err)
		http.Error(w, "catalog decode: "+err.Error(), http.StatusInternalServerError)
		return
	}

	id, err := AllocateSessionID()
	if err != nil {
		http.Error(w, "alloc id: "+err.Error(), http.StatusInternalServerError)
		return
	}
	meta := map[string]any{
		"label":      "puzzles page-load",
		"created_at": time.Now().Unix(),
	}
	metaJSON, _ := json.MarshalIndent(meta, "", "  ")
	if err := WriteSessionFile(id, "meta.json", append(metaJSON, '\n')); err != nil {
		http.Error(w, "write meta: "+err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	resp := struct {
		SessionID int64             `json:"session_id"`
		Puzzles   []json.RawMessage `json:"puzzles"`
	}{
		SessionID: id,
		Puzzles:   catalog.Puzzles,
	}
	if err := json.NewEncoder(w).Encode(resp); err != nil {
		log.Printf("puzzles catalog: encode err=%v", err)
	}
}
