// GENERATED by cmd/fixturegen — DO NOT EDIT.
// Source scenarios: lynrummy/conformance/scenarios/*.dsl
// Regenerate with: go run ./cmd/fixturegen ./lynrummy/conformance/scenarios/*.dsl

package tricks

import (
	"testing"

	"angry-gopher/lynrummy"
)

// Hand 6H right-extends a loose 1-card 5H stack to a 2-card Incomplete — regression guard for maybeMerge.
func Test_direct_play_extends_loose_card(t *testing.T) {
	hand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 6, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}}
	board := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 50})}
	plays := DirectPlay.FindPlays(hand, board)
	if len(plays) == 0 {
		t.Fatal("expected a play, got none")
	}
	gotBoard, gotHand := plays[0].Apply(board)
	wantHand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 6, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}}
	wantBoard := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}}, lynrummy.Location{Top: 10, Left: 50})}
	if !handsEqualDSL(gotHand, wantHand) {
		t.Fatalf("hand mismatch:\n  want %v\n  got  %v", wantHand, gotHand)
	}
	if !boardsEqualDSL(gotBoard, wantBoard) {
		t.Fatalf("board mismatch:\n  want %v\n  got  %v", wantBoard, gotBoard)
	}
}

// Hand 2H extends a 3H-4H-5H run at the left end. Stack loc shifts left by CardWidth+6 (=33).
func Test_direct_play_left_extend_heart_run(t *testing.T) {
	hand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 2, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}}
	board := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 3, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 4, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 200})}
	plays := DirectPlay.FindPlays(hand, board)
	if len(plays) == 0 {
		t.Fatal("expected a play, got none")
	}
	gotBoard, gotHand := plays[0].Apply(board)
	wantHand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 2, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}}
	wantBoard := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 2, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}, {Card: lynrummy.Card{Value: 3, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 4, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 167})}
	if !handsEqualDSL(gotHand, wantHand) {
		t.Fatalf("hand mismatch:\n  want %v\n  got  %v", wantHand, gotHand)
	}
	if !boardsEqualDSL(gotBoard, wantBoard) {
		t.Fatalf("board mismatch:\n  want %v\n  got  %v", wantBoard, gotBoard)
	}
}

// Hand 9D cannot extend any existing stack.
func Test_direct_play_no_plays(t *testing.T) {
	hand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 9, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.HandNormal}}
	board := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10})}
	plays := DirectPlay.FindPlays(hand, board)
	if len(plays) != 0 {
		t.Fatalf("expected no plays, got %d", len(plays))
	}
}

// Hand 8H extends a 5H-6H-7H pure run at the right end.
func Test_direct_play_right_extend_heart_run(t *testing.T) {
	hand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 8, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}}
	board := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10})}
	plays := DirectPlay.FindPlays(hand, board)
	if len(plays) == 0 {
		t.Fatal("expected a play, got none")
	}
	gotBoard, gotHand := plays[0].Apply(board)
	wantHand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 8, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}}
	wantBoard := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 8, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}}, lynrummy.Location{Top: 10, Left: 10})}
	if !handsEqualDSL(gotHand, wantHand) {
		t.Fatalf("hand mismatch:\n  want %v\n  got  %v", wantHand, gotHand)
	}
	if !boardsEqualDSL(gotBoard, wantBoard) {
		t.Fatalf("board mismatch:\n  want %v\n  got  %v", wantBoard, gotBoard)
	}
}

// Hand has no 3+ group forming a set or run.
func Test_hand_stacks_no_plays(t *testing.T) {
	hand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 7, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}, {Card: lynrummy.Card{Value: 2, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.HandNormal}}
	board := []lynrummy.CardStack(nil)
	plays := HandStacks.FindPlays(hand, board)
	if len(plays) != 0 {
		t.Fatalf("expected no plays, got %d", len(plays))
	}
}

// Hand 2C-3C-4C pushed as a new stack at DUMMY_LOC.
func Test_hand_stacks_pure_run(t *testing.T) {
	hand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 2, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.HandNormal}, {Card: lynrummy.Card{Value: 3, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.HandNormal}, {Card: lynrummy.Card{Value: 4, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.HandNormal}}
	board := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 1, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 2, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 3, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10})}
	plays := HandStacks.FindPlays(hand, board)
	if len(plays) == 0 {
		t.Fatal("expected a play, got none")
	}
	gotBoard, gotHand := plays[0].Apply(board)
	wantHand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 2, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.HandNormal}, {Card: lynrummy.Card{Value: 3, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.HandNormal}, {Card: lynrummy.Card{Value: 4, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.HandNormal}}
	wantBoard := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 1, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 2, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 3, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10}), lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 2, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}, {Card: lynrummy.Card{Value: 3, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}, {Card: lynrummy.Card{Value: 4, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}}, lynrummy.Location{Top: 0, Left: 0})}
	if !handsEqualDSL(gotHand, wantHand) {
		t.Fatalf("hand mismatch:\n  want %v\n  got  %v", wantHand, gotHand)
	}
	if !boardsEqualDSL(gotBoard, wantBoard) {
		t.Fatalf("board mismatch:\n  want %v\n  got  %v", wantBoard, gotBoard)
	}
}

// Hand 7H-7S-7D pushed as a new 3-set.
func Test_hand_stacks_set(t *testing.T) {
	hand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 7, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.HandNormal}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.HandNormal}}
	board := []lynrummy.CardStack(nil)
	plays := HandStacks.FindPlays(hand, board)
	if len(plays) == 0 {
		t.Fatal("expected a play, got none")
	}
	gotBoard, gotHand := plays[0].Apply(board)
	wantHand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 7, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.HandNormal}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.HandNormal}}
	wantBoard := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 7, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}}, lynrummy.Location{Top: 0, Left: 0})}
	if !handsEqualDSL(gotHand, wantHand) {
		t.Fatalf("hand mismatch:\n  want %v\n  got  %v", wantHand, gotHand)
	}
	if !boardsEqualDSL(gotBoard, wantBoard) {
		t.Fatalf("board mismatch:\n  want %v\n  got  %v", wantBoard, gotBoard)
	}
}

// Player adds cards to the board that weren't in removed stacks or declared hand.
func Test_inventory_card_from_nowhere(t *testing.T) {
	bounds := lynrummy.BoardBounds{MaxWidth: 800, MaxHeight: 600, Margin: 5}
	boardBefore := []lynrummy.CardStack(nil)
	stacksToRemove := []lynrummy.CardStack(nil)
	stacksToAdd := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 1, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}, {Card: lynrummy.Card{Value: 2, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}, {Card: lynrummy.Card{Value: 3, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}}, lynrummy.Location{Top: 10, Left: 10})}
	hand := []lynrummy.Card{lynrummy.Card{Value: 1, Suit: lynrummy.Heart, OriginDeck: 0}, lynrummy.Card{Value: 2, Suit: lynrummy.Heart, OriginDeck: 0}}
	got := lynrummy.ValidateGameMove(lynrummy.Move{BoardBefore: boardBefore, StacksToRemove: stacksToRemove, StacksToAdd: stacksToAdd, HandCardsPlayed: hand}, bounds)
	if got == nil {
		t.Fatal("expected error at stage \"inventory\", got ok")
	}
	if got.Stage != "inventory" {
		t.Fatalf("stage: want \"inventory\", got %q", got.Stage)
	}
	if !stringsContainsDSL(got.Message, "no source") {
		t.Fatalf("message: want substring \"no source\", got %q", got.Message)
	}
}

// Hand 8H is stranded. Peel 7H off a 4-set onto [4H,5H,6H]; 8H then extends.
func Test_loose_card_play_7H_to_heart_run(t *testing.T) {
	hand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 8, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}}
	board := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 4, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10}), lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 7, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 200})}
	plays := LooseCardPlay.FindPlays(hand, board)
	if len(plays) == 0 {
		t.Fatal("expected a play, got none")
	}
	gotBoard, gotHand := plays[0].Apply(board)
	wantHand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 8, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}}
	wantBoard := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 4, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}, {Card: lynrummy.Card{Value: 8, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}}, lynrummy.Location{Top: 10, Left: 10}), lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 7, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 200})}
	if !handsEqualDSL(gotHand, wantHand) {
		t.Fatalf("hand mismatch:\n  want %v\n  got  %v", wantHand, gotHand)
	}
	if !boardsEqualDSL(gotBoard, wantBoard) {
		t.Fatalf("board mismatch:\n  want %v\n  got  %v", wantBoard, gotBoard)
	}
}

// Mid-turn boards may contain incomplete/bogus stacks; ValidateGameMove doesn't check semantics.
func Test_midturn_allows_bogus(t *testing.T) {
	bounds := lynrummy.BoardBounds{MaxWidth: 800, MaxHeight: 600, Margin: 5}
	boardBefore := []lynrummy.CardStack(nil)
	stacksToRemove := []lynrummy.CardStack(nil)
	stacksToAdd := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 1, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}, {Card: lynrummy.Card{Value: 5, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}, {Card: lynrummy.Card{Value: 13, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}}, lynrummy.Location{Top: 10, Left: 10})}
	hand := []lynrummy.Card{lynrummy.Card{Value: 1, Suit: lynrummy.Heart, OriginDeck: 0}, lynrummy.Card{Value: 5, Suit: lynrummy.Club, OriginDeck: 0}, lynrummy.Card{Value: 13, Suit: lynrummy.Diamond, OriginDeck: 0}}
	got := lynrummy.ValidateGameMove(lynrummy.Move{BoardBefore: boardBefore, StacksToRemove: stacksToRemove, StacksToAdd: stacksToAdd, HandCardsPlayed: hand}, bounds)
	if got != nil {
		t.Fatalf("expected ok, got %s: %s", got.Stage, got.Message)
	}
}

// Hand JS+QH (rb pair); peel TD off a pure diamond run to complete [TD, JS, QH] rb run.
func Test_pair_peel_rb_from_pure_run(t *testing.T) {
	hand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 11, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.HandNormal}, {Card: lynrummy.Card{Value: 12, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}}
	board := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 10, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 11, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 12, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 13, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10})}
	plays := PairPeel.FindPlays(hand, board)
	if len(plays) == 0 {
		t.Fatal("expected a play, got none")
	}
	gotBoard, gotHand := plays[0].Apply(board)
	wantHand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 11, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.HandNormal}, {Card: lynrummy.Card{Value: 12, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}}
	wantBoard := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 11, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 12, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 13, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10}), lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 10, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 11, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}, {Card: lynrummy.Card{Value: 12, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}}, lynrummy.Location{Top: 0, Left: 0})}
	if !handsEqualDSL(gotHand, wantHand) {
		t.Fatalf("hand mismatch:\n  want %v\n  got  %v", wantHand, gotHand)
	}
	if !boardsEqualDSL(gotBoard, wantBoard) {
		t.Fatalf("board mismatch:\n  want %v\n  got  %v", wantBoard, gotBoard)
	}
}

// Hand 5H; peel 4S + 6S off two 4-sets; new rb run [4S, 5H, 6S].
func Test_peel_for_run_rb_triple(t *testing.T) {
	hand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}}
	board := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 4, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 4, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 4, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 4, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10}), lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 6, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 200})}
	plays := PeelForRun.FindPlays(hand, board)
	if len(plays) == 0 {
		t.Fatal("expected a play, got none")
	}
	gotBoard, gotHand := plays[0].Apply(board)
	wantHand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}}
	wantBoard := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 4, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 4, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 4, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10}), lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 6, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 200}), lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 4, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 0, Left: 0})}
	if !handsEqualDSL(gotHand, wantHand) {
		t.Fatalf("hand mismatch:\n  want %v\n  got  %v", wantHand, gotHand)
	}
	if !boardsEqualDSL(gotBoard, wantBoard) {
		t.Fatalf("board mismatch:\n  want %v\n  got  %v", wantBoard, gotBoard)
	}
}

// Hand 5D swaps into an rb run at the 5H seat; kicked 5H extends a pure hearts run.
func Test_rb_swap_5D_into_rb_run(t *testing.T) {
	hand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.HandNormal}}
	board := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 8, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10}), lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 2, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 3, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 4, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 200})}
	plays := RbSwap.FindPlays(hand, board)
	if len(plays) == 0 {
		t.Fatal("expected a play, got none")
	}
	gotBoard, gotHand := plays[0].Apply(board)
	wantHand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.HandNormal}}
	wantBoard := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 8, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10}), lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 2, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 3, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 4, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}}, lynrummy.Location{Top: 10, Left: 200})}
	if !handsEqualDSL(gotHand, wantHand) {
		t.Fatalf("hand mismatch:\n  want %v\n  got  %v", wantHand, gotHand)
	}
	if !boardsEqualDSL(gotBoard, wantBoard) {
		t.Fatalf("board mismatch:\n  want %v\n  got  %v", wantBoard, gotBoard)
	}
}

// Hand 8H; pull 8S + 8D off two size-4 pure runs; new 3-set of 8s.
func Test_split_for_set_eights(t *testing.T) {
	hand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 8, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}}
	board := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 8, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10}), lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 8, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 200})}
	plays := SplitForSet.FindPlays(hand, board)
	if len(plays) == 0 {
		t.Fatal("expected a play, got none")
	}
	gotBoard, gotHand := plays[0].Apply(board)
	wantHand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 8, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}}
	wantBoard := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10}), lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 200}), lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 8, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}, {Card: lynrummy.Card{Value: 8, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 8, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 0, Left: 0})}
	if !handsEqualDSL(gotHand, wantHand) {
		t.Fatalf("hand mismatch:\n  want %v\n  got  %v", wantHand, gotHand)
	}
	if !boardsEqualDSL(gotBoard, wantBoard) {
		t.Fatalf("board mismatch:\n  want %v\n  got  %v", wantBoard, gotBoard)
	}
}

// Hand 8H finds no same-value extractable board cards.
func Test_split_for_set_no_plays(t *testing.T) {
	hand := []lynrummy.HandCard{{Card: lynrummy.Card{Value: 8, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.HandNormal}}
	board := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 1, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 2, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 3, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10})}
	plays := SplitForSet.FindPlays(hand, board)
	if len(plays) != 0 {
		t.Fatalf("expected no plays, got %d", len(plays))
	}
}

// Every stack on the board is a valid group (run + set, well-spaced).
func Test_turn_complete_clean_board(t *testing.T) {
	bounds := lynrummy.BoardBounds{MaxWidth: 800, MaxHeight: 600, Margin: 5}
	board := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 1, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 2, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 3, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10}), lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 13, Suit: lynrummy.Club, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 13, Suit: lynrummy.Diamond, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 13, Suit: lynrummy.Spade, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 200})}
	got := lynrummy.ValidateTurnComplete(board, bounds)
	if got != nil {
		t.Fatalf("expected ok, got %s: %s", got.Stage, got.Message)
	}
}

// Two-card stack fine mid-turn but rejected at turn-complete.
func Test_turn_complete_rejects_incomplete(t *testing.T) {
	bounds := lynrummy.BoardBounds{MaxWidth: 800, MaxHeight: 600, Margin: 5}
	board := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 1, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 2, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10})}
	got := lynrummy.ValidateTurnComplete(board, bounds)
	if got == nil {
		t.Fatal("expected error at stage \"semantics\", got ok")
	}
	if got.Stage != "semantics" {
		t.Fatalf("stage: want \"semantics\", got %q", got.Stage)
	}
	if !stringsContainsDSL(got.Message, "incomplete") {
		t.Fatalf("message: want substring \"incomplete\", got %q", got.Message)
	}
}

// Player extends a 5H-6H-7H run by playing 8H from hand.
func Test_valid_extend_run_with_8H(t *testing.T) {
	bounds := lynrummy.BoardBounds{MaxWidth: 800, MaxHeight: 600, Margin: 5}
	boardBefore := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10})}
	stacksToRemove := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}}, lynrummy.Location{Top: 10, Left: 10})}
	stacksToAdd := []lynrummy.CardStack{lynrummy.NewCardStack([]lynrummy.BoardCard{{Card: lynrummy.Card{Value: 5, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 6, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 7, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FirmlyOnBoard}, {Card: lynrummy.Card{Value: 8, Suit: lynrummy.Heart, OriginDeck: 0}, State: lynrummy.FreshlyPlayed}}, lynrummy.Location{Top: 10, Left: 10})}
	hand := []lynrummy.Card{lynrummy.Card{Value: 8, Suit: lynrummy.Heart, OriginDeck: 0}}
	got := lynrummy.ValidateGameMove(lynrummy.Move{BoardBefore: boardBefore, StacksToRemove: stacksToRemove, StacksToAdd: stacksToAdd, HandCardsPlayed: hand}, bounds)
	if got != nil {
		t.Fatalf("expected ok, got %s: %s", got.Stage, got.Message)
	}
}
