module LynRummy.Fixtures exposing (fixtures)

{-| GENERATED FILE — DO NOT EDIT BY HAND.

Regenerate with:
  python3 angry-gopher/tools/gen_elm_fixtures.py

Source: angry-gopher/lynrummy/conformance/*.json

Each tuple is (fixture-name, raw-JSON). The test suite decodes the
raw JSON at test time, so parser bugs in Elm decoders surface as
fixture failures.
-}


fixtures : List ( String, String )
fixtures =
    [ ( "geometry_out_of_bounds", """{"name":"geometry_out_of_bounds","description":"A 3-card stack at left=780 extends past max_width=800.","operation":"validate_game_move","input":{"board_before":[],"stacks_to_remove":[],"stacks_to_add":[{"board_cards":[{"card":{"value":1,"suit":3,"origin_deck":0},"state":1},{"card":{"value":2,"suit":3,"origin_deck":0},"state":1},{"card":{"value":3,"suit":3,"origin_deck":0},"state":1}],"loc":{"top":10,"left":780}}],"hand_cards_played":[{"card":{"value":1,"suit":3,"origin_deck":0},"state":0},{"card":{"value":2,"suit":3,"origin_deck":0},"state":0},{"card":{"value":3,"suit":3,"origin_deck":0},"state":0}]},"bounds":{"max_width":800,"max_height":600,"margin":5},"expected":{"ok":false,"error":{"stage":"geometry","message_substr":"outside the board"}}}""" ),
      ( "geometry_overlap", """{"name":"geometry_overlap","description":"Player adds a stack at the same loc as an existing stack — geometry rejects the overlap.","operation":"validate_game_move","input":{"board_before":[{"board_cards":[{"card":{"value":1,"suit":3,"origin_deck":0},"state":0},{"card":{"value":2,"suit":3,"origin_deck":0},"state":0},{"card":{"value":3,"suit":3,"origin_deck":0},"state":0}],"loc":{"top":10,"left":10}}],"stacks_to_remove":[],"stacks_to_add":[{"board_cards":[{"card":{"value":7,"suit":0,"origin_deck":0},"state":1},{"card":{"value":7,"suit":1,"origin_deck":0},"state":1},{"card":{"value":7,"suit":2,"origin_deck":0},"state":1}],"loc":{"top":10,"left":10}}],"hand_cards_played":[{"card":{"value":7,"suit":0,"origin_deck":0},"state":0},{"card":{"value":7,"suit":1,"origin_deck":0},"state":0},{"card":{"value":7,"suit":2,"origin_deck":0},"state":0}]},"bounds":{"max_width":800,"max_height":600,"margin":5},"expected":{"ok":false,"error":{"stage":"geometry","message_substr":"overlap"}}}""" ),
      ( "inventory_card_from_nowhere", """{"name":"inventory_card_from_nowhere","description":"Player adds AH-2H-3H but only declared AH and 2H from hand. The 3H has no source.","operation":"validate_game_move","input":{"board_before":[],"stacks_to_remove":[],"stacks_to_add":[{"board_cards":[{"card":{"value":1,"suit":3,"origin_deck":0},"state":1},{"card":{"value":2,"suit":3,"origin_deck":0},"state":1},{"card":{"value":3,"suit":3,"origin_deck":0},"state":1}],"loc":{"top":10,"left":10}}],"hand_cards_played":[{"card":{"value":1,"suit":3,"origin_deck":0},"state":0},{"card":{"value":2,"suit":3,"origin_deck":0},"state":0}]},"bounds":{"max_width":800,"max_height":600,"margin":5},"expected":{"ok":false,"error":{"stage":"inventory","message_substr":"no source"}}}""" ),
      ( "inventory_missing_remove", """{"name":"inventory_missing_remove","description":"Player references a phantom stack in stacks_to_remove that isn't actually on the board.","operation":"validate_game_move","input":{"board_before":[],"stacks_to_remove":[{"board_cards":[{"card":{"value":1,"suit":3,"origin_deck":0},"state":0},{"card":{"value":2,"suit":3,"origin_deck":0},"state":0},{"card":{"value":3,"suit":3,"origin_deck":0},"state":0}],"loc":{"top":10,"left":10}}],"stacks_to_add":[]},"bounds":{"max_width":800,"max_height":600,"margin":5},"expected":{"ok":false,"error":{"stage":"inventory","message_substr":"not on the board"}}}""" ),
      ( "inventory_unplaced_hand_card", """{"name":"inventory_unplaced_hand_card","description":"Player declared 4 hand cards (AH, 2H, 3H, 4H) but only placed 3 (AH, 2H, 3H). The 4H is unplaced.","operation":"validate_game_move","input":{"board_before":[],"stacks_to_remove":[],"stacks_to_add":[{"board_cards":[{"card":{"value":1,"suit":3,"origin_deck":0},"state":1},{"card":{"value":2,"suit":3,"origin_deck":0},"state":1},{"card":{"value":3,"suit":3,"origin_deck":0},"state":1}],"loc":{"top":10,"left":10}}],"hand_cards_played":[{"card":{"value":1,"suit":3,"origin_deck":0},"state":0},{"card":{"value":2,"suit":3,"origin_deck":0},"state":0},{"card":{"value":3,"suit":3,"origin_deck":0},"state":0},{"card":{"value":4,"suit":3,"origin_deck":0},"state":0}]},"bounds":{"max_width":800,"max_height":600,"margin":5},"expected":{"ok":false,"error":{"stage":"inventory","message_substr":"not placed"}}}""" ),
      ( "midturn_allows_bogus", """{"name":"midturn_allows_bogus","description":"Mid-turn validation accepts a semantically bogus stack (AH, 5C, KD). Semantics is only enforced at turn boundary.","operation":"validate_game_move","input":{"board_before":[],"stacks_to_remove":[],"stacks_to_add":[{"board_cards":[{"card":{"value":1,"suit":3,"origin_deck":0},"state":1},{"card":{"value":5,"suit":0,"origin_deck":0},"state":1},{"card":{"value":13,"suit":1,"origin_deck":0},"state":1}],"loc":{"top":10,"left":10}}],"hand_cards_played":[{"card":{"value":1,"suit":3,"origin_deck":0},"state":0},{"card":{"value":5,"suit":0,"origin_deck":0},"state":0},{"card":{"value":13,"suit":1,"origin_deck":0},"state":0}]},"bounds":{"max_width":800,"max_height":600,"margin":5},"expected":{"ok":true}}""" ),
      ( "turn_complete_clean_board", """{"name":"turn_complete_clean_board","description":"Turn-complete check passes when every stack on the board is a valid group (a run and a set, well-spaced).","operation":"validate_turn_complete","input":{"board":[{"board_cards":[{"card":{"value":1,"suit":3,"origin_deck":0},"state":0},{"card":{"value":2,"suit":3,"origin_deck":0},"state":0},{"card":{"value":3,"suit":3,"origin_deck":0},"state":0}],"loc":{"top":10,"left":10}},{"board_cards":[{"card":{"value":13,"suit":0,"origin_deck":0},"state":0},{"card":{"value":13,"suit":1,"origin_deck":0},"state":0},{"card":{"value":13,"suit":2,"origin_deck":0},"state":0}],"loc":{"top":10,"left":200}}]},"bounds":{"max_width":800,"max_height":600,"margin":5},"expected":{"ok":true}}""" ),
      ( "turn_complete_rejects_incomplete", """{"name":"turn_complete_rejects_incomplete","description":"Two-card stack is allowed mid-turn but rejected at turn-complete (semantics enforces minimum 3-card groups).","operation":"validate_turn_complete","input":{"board":[{"board_cards":[{"card":{"value":1,"suit":3,"origin_deck":0},"state":0},{"card":{"value":2,"suit":3,"origin_deck":0},"state":0}],"loc":{"top":10,"left":10}}]},"bounds":{"max_width":800,"max_height":600,"margin":5},"expected":{"ok":false,"error":{"stage":"semantics","message_substr":"incomplete"}}}""" ),
      ( "valid_extend_run_with_8H", """{"name":"valid_extend_run_with_8H","description":"Player extends a 5H-6H-7H run by playing the 8 of hearts from hand. Happy path.","operation":"validate_game_move","input":{"board_before":[{"board_cards":[{"card":{"value":5,"suit":3,"origin_deck":0},"state":0},{"card":{"value":6,"suit":3,"origin_deck":0},"state":0},{"card":{"value":7,"suit":3,"origin_deck":0},"state":0}],"loc":{"top":10,"left":10}}],"stacks_to_remove":[{"board_cards":[{"card":{"value":5,"suit":3,"origin_deck":0},"state":0},{"card":{"value":6,"suit":3,"origin_deck":0},"state":0},{"card":{"value":7,"suit":3,"origin_deck":0},"state":0}],"loc":{"top":10,"left":10}}],"stacks_to_add":[{"board_cards":[{"card":{"value":5,"suit":3,"origin_deck":0},"state":0},{"card":{"value":6,"suit":3,"origin_deck":0},"state":0},{"card":{"value":7,"suit":3,"origin_deck":0},"state":0},{"card":{"value":8,"suit":3,"origin_deck":0},"state":1}],"loc":{"top":10,"left":10}}],"hand_cards_played":[{"card":{"value":8,"suit":3,"origin_deck":0},"state":0}]},"bounds":{"max_width":800,"max_height":600,"margin":5},"expected":{"ok":true}}""" ),
      ( "valid_split_long_run", """{"name":"valid_split_long_run","description":"Player splits a 6-card 3D-8D run into two 3-card halves. Pure rearrangement, no hand cards.","operation":"validate_game_move","input":{"board_before":[{"board_cards":[{"card":{"value":3,"suit":1,"origin_deck":0},"state":0},{"card":{"value":4,"suit":1,"origin_deck":0},"state":0},{"card":{"value":5,"suit":1,"origin_deck":0},"state":0},{"card":{"value":6,"suit":1,"origin_deck":0},"state":0},{"card":{"value":7,"suit":1,"origin_deck":0},"state":0},{"card":{"value":8,"suit":1,"origin_deck":0},"state":0}],"loc":{"top":10,"left":10}}],"stacks_to_remove":[{"board_cards":[{"card":{"value":3,"suit":1,"origin_deck":0},"state":0},{"card":{"value":4,"suit":1,"origin_deck":0},"state":0},{"card":{"value":5,"suit":1,"origin_deck":0},"state":0},{"card":{"value":6,"suit":1,"origin_deck":0},"state":0},{"card":{"value":7,"suit":1,"origin_deck":0},"state":0},{"card":{"value":8,"suit":1,"origin_deck":0},"state":0}],"loc":{"top":10,"left":10}}],"stacks_to_add":[{"board_cards":[{"card":{"value":3,"suit":1,"origin_deck":0},"state":0},{"card":{"value":4,"suit":1,"origin_deck":0},"state":0},{"card":{"value":5,"suit":1,"origin_deck":0},"state":0}],"loc":{"top":10,"left":10}},{"board_cards":[{"card":{"value":6,"suit":1,"origin_deck":0},"state":0},{"card":{"value":7,"suit":1,"origin_deck":0},"state":0},{"card":{"value":8,"suit":1,"origin_deck":0},"state":0}],"loc":{"top":10,"left":200}}]},"bounds":{"max_width":800,"max_height":600,"margin":5},"expected":{"ok":true}}""" )
    ]
