// GENERATED by cmd/fixturegen — DO NOT EDIT.
// Source scenarios: lynrummy/conformance/scenarios/*.dsl
// Regenerate with: go run ./cmd/fixturegen ./lynrummy/conformance/scenarios/*.dsl

package lynrummy

import (
	"strings"
	"testing"
)

// Client's stacks_to_remove has the wrong originDeck; must not match the board stack (fabrication guard).
func Test_deck_identity_mismatch_in_remove(t *testing.T) {
	bounds := BoardBounds{MaxWidth: 800, MaxHeight: 600, Margin: 5}
	boardBefore := []CardStack{NewCardStack([]BoardCard{{Card: Card{Value: 5, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 6, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 7, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}}, Location{Top: 10, Left: 10})}
	stacksToRemove := []CardStack{NewCardStack([]BoardCard{{Card: Card{Value: 5, Suit: Heart, OriginDeck: 1}, State: FirmlyOnBoard}, {Card: Card{Value: 6, Suit: Heart, OriginDeck: 1}, State: FirmlyOnBoard}, {Card: Card{Value: 7, Suit: Heart, OriginDeck: 1}, State: FirmlyOnBoard}}, Location{Top: 10, Left: 10})}
	stacksToAdd := []CardStack{NewCardStack([]BoardCard{{Card: Card{Value: 5, Suit: Heart, OriginDeck: 1}, State: FirmlyOnBoard}, {Card: Card{Value: 6, Suit: Heart, OriginDeck: 1}, State: FirmlyOnBoard}, {Card: Card{Value: 7, Suit: Heart, OriginDeck: 1}, State: FirmlyOnBoard}, {Card: Card{Value: 8, Suit: Heart, OriginDeck: 1}, State: FreshlyPlayed}}, Location{Top: 10, Left: 10})}
	hand := []Card{Card{Value: 8, Suit: Heart, OriginDeck: 1}}
	got := ValidateGameMove(Move{BoardBefore: boardBefore, StacksToRemove: stacksToRemove, StacksToAdd: stacksToAdd, HandCardsPlayed: hand}, bounds)
	if got == nil {
		t.Fatal("expected error at stage \"inventory\", got ok")
	}
	if got.Stage != "inventory" {
		t.Fatalf("stage: want \"inventory\", got %q", got.Stage)
	}
	if !strings.Contains(got.Message, "not on the board") {
		t.Fatalf("message: want substring \"not on the board\", got %q", got.Message)
	}
}

// Two stacks within BoardBounds.margin (5px) but not overlapping.
func Test_geometry_crowded(t *testing.T) {
	bounds := BoardBounds{MaxWidth: 800, MaxHeight: 600, Margin: 5}
	boardBefore := []CardStack(nil)
	stacksToRemove := []CardStack(nil)
	stacksToAdd := []CardStack{NewCardStack([]BoardCard{{Card: Card{Value: 1, Suit: Heart, OriginDeck: 0}, State: FreshlyPlayed}}, Location{Top: 10, Left: 10}), NewCardStack([]BoardCard{{Card: Card{Value: 2, Suit: Spade, OriginDeck: 0}, State: FreshlyPlayed}}, Location{Top: 10, Left: 40})}
	hand := []Card{Card{Value: 1, Suit: Heart, OriginDeck: 0}, Card{Value: 2, Suit: Spade, OriginDeck: 0}}
	got := ValidateGameMove(Move{BoardBefore: boardBefore, StacksToRemove: stacksToRemove, StacksToAdd: stacksToAdd, HandCardsPlayed: hand}, bounds)
	if got == nil {
		t.Fatal("expected error at stage \"geometry\", got ok")
	}
	if got.Stage != "geometry" {
		t.Fatalf("stage: want \"geometry\", got %q", got.Stage)
	}
	if !strings.Contains(got.Message, "too close") {
		t.Fatalf("message: want substring \"too close\", got %q", got.Message)
	}
}

// Stack whose right edge exceeds MaxWidth is rejected.
func Test_geometry_out_of_bounds(t *testing.T) {
	bounds := BoardBounds{MaxWidth: 800, MaxHeight: 600, Margin: 5}
	boardBefore := []CardStack(nil)
	stacksToRemove := []CardStack(nil)
	stacksToAdd := []CardStack{NewCardStack([]BoardCard{{Card: Card{Value: 1, Suit: Heart, OriginDeck: 0}, State: FreshlyPlayed}}, Location{Top: 10, Left: 790})}
	hand := []Card{Card{Value: 1, Suit: Heart, OriginDeck: 0}}
	got := ValidateGameMove(Move{BoardBefore: boardBefore, StacksToRemove: stacksToRemove, StacksToAdd: stacksToAdd, HandCardsPlayed: hand}, bounds)
	if got == nil {
		t.Fatal("expected error at stage \"geometry\", got ok")
	}
	if got.Stage != "geometry" {
		t.Fatalf("stage: want \"geometry\", got %q", got.Stage)
	}
	if !strings.Contains(got.Message, "outside") {
		t.Fatalf("message: want substring \"outside\", got %q", got.Message)
	}
}

// Two stacks at the same coordinates actually overlap.
func Test_geometry_overlap(t *testing.T) {
	bounds := BoardBounds{MaxWidth: 800, MaxHeight: 600, Margin: 5}
	boardBefore := []CardStack(nil)
	stacksToRemove := []CardStack(nil)
	stacksToAdd := []CardStack{NewCardStack([]BoardCard{{Card: Card{Value: 1, Suit: Heart, OriginDeck: 0}, State: FreshlyPlayed}}, Location{Top: 10, Left: 10}), NewCardStack([]BoardCard{{Card: Card{Value: 2, Suit: Spade, OriginDeck: 0}, State: FreshlyPlayed}}, Location{Top: 10, Left: 10})}
	hand := []Card{Card{Value: 1, Suit: Heart, OriginDeck: 0}, Card{Value: 2, Suit: Spade, OriginDeck: 0}}
	got := ValidateGameMove(Move{BoardBefore: boardBefore, StacksToRemove: stacksToRemove, StacksToAdd: stacksToAdd, HandCardsPlayed: hand}, bounds)
	if got == nil {
		t.Fatal("expected error at stage \"geometry\", got ok")
	}
	if got.Stage != "geometry" {
		t.Fatalf("stage: want \"geometry\", got %q", got.Stage)
	}
	if !strings.Contains(got.Message, "overlap") {
		t.Fatalf("message: want substring \"overlap\", got %q", got.Message)
	}
}

// A set on the board is referenced in stacks_to_remove with cards in a different order. Stacks are identified by loc + cards-in-order, so the reordered copy is NOT the same stack — referee rejects at inventory stage. Exercises the strict-order rule end-to-end; sets are the natural case since their player-visible form has no canonical order.
func Test_identity_reorder_breaks_match(t *testing.T) {
	bounds := BoardBounds{MaxWidth: 800, MaxHeight: 600, Margin: 5}
	boardBefore := []CardStack{NewCardStack([]BoardCard{{Card: Card{Value: 5, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 5, Suit: Club, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 5, Suit: Spade, OriginDeck: 0}, State: FirmlyOnBoard}}, Location{Top: 100, Left: 100})}
	stacksToRemove := []CardStack{NewCardStack([]BoardCard{{Card: Card{Value: 5, Suit: Club, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 5, Suit: Spade, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 5, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}}, Location{Top: 100, Left: 100})}
	stacksToAdd := []CardStack{NewCardStack([]BoardCard{{Card: Card{Value: 5, Suit: Club, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 5, Suit: Spade, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 5, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 5, Suit: Diamond, OriginDeck: 0}, State: FreshlyPlayed}}, Location{Top: 100, Left: 100})}
	hand := []Card{Card{Value: 5, Suit: Diamond, OriginDeck: 0}}
	got := ValidateGameMove(Move{BoardBefore: boardBefore, StacksToRemove: stacksToRemove, StacksToAdd: stacksToAdd, HandCardsPlayed: hand}, bounds)
	if got == nil {
		t.Fatal("expected error at stage \"inventory\", got ok")
	}
	if got.Stage != "inventory" {
		t.Fatalf("stage: want \"inventory\", got %q", got.Stage)
	}
	if !strings.Contains(got.Message, "not on the board") {
		t.Fatalf("message: want substring \"not on the board\", got %q", got.Message)
	}
}

// Player adds cards to the board that weren't in removed stacks or declared hand.
func Test_inventory_card_from_nowhere(t *testing.T) {
	bounds := BoardBounds{MaxWidth: 800, MaxHeight: 600, Margin: 5}
	boardBefore := []CardStack(nil)
	stacksToRemove := []CardStack(nil)
	stacksToAdd := []CardStack{NewCardStack([]BoardCard{{Card: Card{Value: 1, Suit: Heart, OriginDeck: 0}, State: FreshlyPlayed}, {Card: Card{Value: 2, Suit: Heart, OriginDeck: 0}, State: FreshlyPlayed}, {Card: Card{Value: 3, Suit: Heart, OriginDeck: 0}, State: FreshlyPlayed}}, Location{Top: 10, Left: 10})}
	hand := []Card{Card{Value: 1, Suit: Heart, OriginDeck: 0}, Card{Value: 2, Suit: Heart, OriginDeck: 0}}
	got := ValidateGameMove(Move{BoardBefore: boardBefore, StacksToRemove: stacksToRemove, StacksToAdd: stacksToAdd, HandCardsPlayed: hand}, bounds)
	if got == nil {
		t.Fatal("expected error at stage \"inventory\", got ok")
	}
	if got.Stage != "inventory" {
		t.Fatalf("stage: want \"inventory\", got %q", got.Stage)
	}
	if !strings.Contains(got.Message, "no source") {
		t.Fatalf("message: want substring \"no source\", got %q", got.Message)
	}
}

// Mid-turn boards may contain incomplete/bogus stacks; ValidateGameMove doesn't check semantics.
func Test_midturn_allows_bogus(t *testing.T) {
	bounds := BoardBounds{MaxWidth: 800, MaxHeight: 600, Margin: 5}
	boardBefore := []CardStack(nil)
	stacksToRemove := []CardStack(nil)
	stacksToAdd := []CardStack{NewCardStack([]BoardCard{{Card: Card{Value: 1, Suit: Heart, OriginDeck: 0}, State: FreshlyPlayed}, {Card: Card{Value: 5, Suit: Club, OriginDeck: 0}, State: FreshlyPlayed}, {Card: Card{Value: 13, Suit: Diamond, OriginDeck: 0}, State: FreshlyPlayed}}, Location{Top: 10, Left: 10})}
	hand := []Card{Card{Value: 1, Suit: Heart, OriginDeck: 0}, Card{Value: 5, Suit: Club, OriginDeck: 0}, Card{Value: 13, Suit: Diamond, OriginDeck: 0}}
	got := ValidateGameMove(Move{BoardBefore: boardBefore, StacksToRemove: stacksToRemove, StacksToAdd: stacksToAdd, HandCardsPlayed: hand}, bounds)
	if got != nil {
		t.Fatalf("expected ok, got %s: %s", got.Stage, got.Message)
	}
}

// Every stack on the board is a valid group (run + set, well-spaced).
func Test_turn_complete_clean_board(t *testing.T) {
	bounds := BoardBounds{MaxWidth: 800, MaxHeight: 600, Margin: 5}
	board := []CardStack{NewCardStack([]BoardCard{{Card: Card{Value: 1, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 2, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 3, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}}, Location{Top: 10, Left: 10}), NewCardStack([]BoardCard{{Card: Card{Value: 13, Suit: Club, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 13, Suit: Diamond, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 13, Suit: Spade, OriginDeck: 0}, State: FirmlyOnBoard}}, Location{Top: 10, Left: 200})}
	got := ValidateTurnComplete(board, bounds)
	if got != nil {
		t.Fatalf("expected ok, got %s: %s", got.Stage, got.Message)
	}
}

// Two-card stack fine mid-turn but rejected at turn-complete.
func Test_turn_complete_rejects_incomplete(t *testing.T) {
	bounds := BoardBounds{MaxWidth: 800, MaxHeight: 600, Margin: 5}
	board := []CardStack{NewCardStack([]BoardCard{{Card: Card{Value: 1, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 2, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}}, Location{Top: 10, Left: 10})}
	got := ValidateTurnComplete(board, bounds)
	if got == nil {
		t.Fatal("expected error at stage \"semantics\", got ok")
	}
	if got.Stage != "semantics" {
		t.Fatalf("stage: want \"semantics\", got %q", got.Stage)
	}
	if !strings.Contains(got.Message, "incomplete") {
		t.Fatalf("message: want substring \"incomplete\", got %q", got.Message)
	}
}

// Player extends a 5H-6H-7H run by playing 8H from hand.
func Test_valid_extend_run_with_8H(t *testing.T) {
	bounds := BoardBounds{MaxWidth: 800, MaxHeight: 600, Margin: 5}
	boardBefore := []CardStack{NewCardStack([]BoardCard{{Card: Card{Value: 5, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 6, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 7, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}}, Location{Top: 10, Left: 10})}
	stacksToRemove := []CardStack{NewCardStack([]BoardCard{{Card: Card{Value: 5, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 6, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 7, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}}, Location{Top: 10, Left: 10})}
	stacksToAdd := []CardStack{NewCardStack([]BoardCard{{Card: Card{Value: 5, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 6, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 7, Suit: Heart, OriginDeck: 0}, State: FirmlyOnBoard}, {Card: Card{Value: 8, Suit: Heart, OriginDeck: 0}, State: FreshlyPlayed}}, Location{Top: 10, Left: 10})}
	hand := []Card{Card{Value: 8, Suit: Heart, OriginDeck: 0}}
	got := ValidateGameMove(Move{BoardBefore: boardBefore, StacksToRemove: stacksToRemove, StacksToAdd: stacksToAdd, HandCardsPlayed: hand}, bounds)
	if got != nil {
		t.Fatalf("expected ok, got %s: %s", got.Stage, got.Message)
	}
}
