// gen_baseline_board.ts — Generate the 81-card baseline gold (TS).
//
// TS port of python/tools/gen_baseline_board.py. The Game 17 board
// (6 helpers, 23 cards) is the fixed fixture. For each of the 81
// remaining cards in the double deck, run the BFS solver and record:
// solvable/no_plan, plan length, timing.
//
// Output:
//   ts/bench/baseline_board_81_gold.txt
//
// Note: the paired DSL file
// (games/lynrummy/conformance/scenarios/baseline_board_81.dsl) is
// language-independent — its plan_lines are the spec, and the Python
// pipeline still emits/maintains the .dsl. This script writes ONLY
// the timing gold. Plan correctness is verified by the conformance
// tests, not by this script.
//
// Usage:
//   node bench/gen_baseline_board.ts

import * as fs from "node:fs";
import * as path from "node:path";

import { type Card, RANKS, SUITS } from "../src/rules/card.ts";
import { timeSolver } from "./bench_timing.ts";
import type { RawBuckets } from "../src/buckets.ts";

const BOARD_LABELS: string[][] = [
  ["KS", "AS", "2S", "3S"],
  ["TD", "JD", "QD", "KD"],
  ["2H", "3H", "4H"],
  ["7S", "7D", "7C"],
  ["AC", "AD", "AH"],
  ["2C", "3D", "4C", "5H", "6S", "7H"],
];

function parseLabel(label: string): Card {
  const rankIdx = RANKS.indexOf(label[0]!);
  const suitIdx = SUITS.indexOf(label[1]!);
  if (rankIdx < 0 || suitIdx < 0) throw new Error(`bad label ${label}`);
  return [rankIdx + 1, suitIdx, 0] as const;
}

function boardSet(): Set<string> {
  const out = new Set<string>();
  for (const stack of BOARD_LABELS) {
    for (const lbl of stack) {
      const c = parseLabel(lbl);
      out.add(`${c[0]},${c[1]},${c[2]}`);
    }
  }
  return out;
}

function allRemaining(): Card[] {
  const onBoard = boardSet();
  const out: Card[] = [];
  for (let si = 0; si < 4; si++) {
    for (let vi = 0; vi < 13; vi++) {
      for (const deck of [0, 1] as const) {
        const c: Card = [vi + 1, si, deck] as const;
        if (!onBoard.has(`${c[0]},${c[1]},${c[2]}`)) out.push(c);
      }
    }
  }
  return out;
}

function dslLabel(c: Card): string {
  const base = RANKS[c[0] - 1] + SUITS[c[1]];
  return c[2] ? `${base}'` : base;
}

function scenarioId(c: Card): string {
  const base = RANKS[c[0] - 1] + SUITS[c[1]];
  return c[2] ? `baseline_board_${base}p` : `baseline_board_${base}`;
}

function helpersAsTuples(): readonly (readonly Card[])[] {
  return BOARD_LABELS.map(stack => stack.map(parseLabel));
}

function timeSolve(c: Card): { plan: readonly { line: string }[] | null; ms: number } {
  const state: RawBuckets = {
    helper: helpersAsTuples(),
    trouble: [[c]],
    growing: [],
    complete: [],
  };
  const { plan, bestMs } = timeSolver(state);
  return { plan, ms: bestMs };
}

function warmupFullPass(cards: readonly Card[]): void {
  process.stderr.write("[warmup] priming the suite (untimed pass)...\n");
  for (const c of cards) {
    const state: RawBuckets = {
      helper: helpersAsTuples(),
      trouble: [[c]],
      growing: [],
      complete: [],
    };
    timeSolver(state, 1);
  }
  process.stderr.write(`[warmup] done (${cards.length} scenarios primed).\n`);
}

const GOLD_HEADER = `\
# baseline_board_81_gold.txt — auto-generated by ts/bench/gen_baseline_board.ts
# Game 17 board (6 helpers, 23 cards) + one trouble singleton per
# remaining card in the double deck. 81 scenarios, sorted by id.
# Columns: <scenario_id>  <ms>  <result>
# Re-run the generator after solver changes; commit alongside the .dsl.
`;

function fmtGoldLine(sid: string, ms: number, result: string): string {
  return sid.padEnd(26) + ms.toFixed(1).padStart(8) + "  " + result;
}

function main(): void {
  const here = path.dirname(new URL(import.meta.url).pathname);
  const goldOut = path.resolve(here, "baseline_board_81_gold.txt");

  const cards = allRemaining();
  if (cards.length !== 81) throw new Error(`expected 81; got ${cards.length}`);

  warmupFullPass(cards);

  const rows: { sid: string; ms: number; result: string }[] = [];
  for (let i = 0; i < cards.length; i++) {
    const c = cards[i]!;
    const label = dslLabel(c);
    const sid = scenarioId(c);
    process.stdout.write(`[${String(i + 1).padStart(2)}/81] ${label.padEnd(5)} ... `);

    const { plan, ms } = timeSolve(c);
    const resultStr = plan === null ? "no_plan" : `${plan.length}-step`;
    console.log(`${resultStr.padEnd(13)}  ${ms.toFixed(1).padStart(7)}ms`);

    rows.push({ sid, ms: Math.round(ms * 10) / 10, result: resultStr });
  }

  rows.sort((a, b) => a.sid.localeCompare(b.sid));
  let body = GOLD_HEADER + "\n";
  for (const r of rows) body += fmtGoldLine(r.sid, r.ms, r.result) + "\n";
  fs.writeFileSync(goldOut, body);
  console.log(`\nWrote ${goldOut}`);

  const noPlan = rows.filter(r => r.result === "no_plan").length;
  const solvable = rows.length - noPlan;
  const slow = rows.filter(r => r.ms > 100).length;
  console.log(`\nSummary: ${solvable} solvable, ${noPlan} no-plan, ${slow} slow (>100ms)`);
}

main();
