"""
export_corpus_to_dsl.py — emit the BFS corpus as DSL
scenarios so cmd/fixturegen can generate matching Python +
Elm conformance fixtures.

The corpus is the 21 puzzle sessions the human/agent ran
through `corpus/sessions.txt`. Each puzzle's initial state
becomes one `solve` scenario asserting the BFS plan-length
matches Python's baseline (the depth distribution from
the post-focus-rule + SPLIT_OUT solver).

This unifies what was a Python-only `corpus_report.py`
correctness check into the cross-language DSL pipeline:

    1. python3 tools/export_corpus_to_dsl.py
    2. go run ./cmd/fixturegen \\
           ./games/lynrummy/conformance/scenarios/*.dsl
    3. python3 games/lynrummy/python/test_dsl_conformance.py
       cd games/lynrummy/elm && ./check.sh

Both runners now assert the corpus depths.

Output goes to `games/lynrummy/conformance/scenarios/
planner_corpus.dsl` (separate from hand-authored
`planner.dsl` so the gen vs hand boundary stays clean).
"""

import json
import sqlite3
from pathlib import Path

DB_PATH = "/home/steve/AngryGopher/prod/gopher.db"
REPO = Path("/home/steve/showell_repos/angry-gopher")
SESSIONS_PATH = REPO / "games/lynrummy/python/corpus/sessions.txt"
OUT_PATH = REPO / "games/lynrummy/conformance/scenarios/planner_corpus.dsl"

# Baseline depth distribution (post-focus-rule + SPLIT_OUT).
# Re-export the DSL whenever the BFS shape changes and the
# baseline shifts.
BASELINE_DEPTHS = [2, 5, 2, 4, 5, 4, 6, 4, 1, 7, 2, 5, 2, 1, 1, 2, 3, 1, 2, 5, 1]

RANKS = "A23456789TJQK"
SUITS = "CDSH"


def card_label_dsl(value, suit, deck):
    """DSL-style label: '5H' for deck-0, '5D'' for deck-1."""
    base = RANKS[value - 1] + SUITS[suit]
    return base + ("'" if deck else "")


def board_for_solver(state):
    """Return (helper_stacks, trouble_label) where helpers are
    the original board stacks (label-string lists) and trouble
    is just the singleton appended from hand."""
    helpers = [
        [
            card_label_dsl(bc["card"]["value"], bc["card"]["suit"],
                           bc["card"]["origin_deck"])
            for bc in stack["board_cards"]
        ]
        for stack in state["board"]
    ]
    hand = state["hands"][state["active_player_index"]]["hand_cards"]
    trouble_card = hand[0]["card"]
    trouble_label = card_label_dsl(
        trouble_card["value"], trouble_card["suit"],
        trouble_card["origin_deck"])
    return helpers, trouble_label


def render_scenario(sid, helpers, trouble, depth):
    """Emit one DSL scenario."""
    lines = []
    lines.append(f"scenario corpus_sid_{sid}")
    lines.append(
        f"  desc: Corpus session {sid}, trouble {trouble}. "
        "Auto-generated; do not hand-edit.")
    lines.append("  op: solve")
    lines.append("  helper:")
    for stack in helpers:
        lines.append(f"    at (0,0): {' '.join(stack)}")
    lines.append("  trouble:")
    lines.append(f"    at (0,0): {trouble}")
    lines.append("  expect:")
    if depth is None:
        # The DSL form for "solver returns no plan."
        lines[-1] = "  expect: no_plan"
    else:
        lines.append(f"    plan_length: {depth}")
    return "\n".join(lines)


def main():
    sids = [int(s.strip()) for s in open(SESSIONS_PATH) if s.strip()]
    if len(sids) != len(BASELINE_DEPTHS):
        raise SystemExit(
            f"sids count {len(sids)} != baseline depths "
            f"count {len(BASELINE_DEPTHS)}")

    conn = sqlite3.connect(DB_PATH)
    scenarios = []
    for sid, depth in zip(sids, BASELINE_DEPTHS):
        row = conn.execute(
            "SELECT initial_state_json FROM lynrummy_puzzle_seeds "
            "WHERE session_id=?", (sid,)).fetchone()
        state = json.loads(row[0])
        helpers, trouble = board_for_solver(state)
        scenarios.append(render_scenario(sid, helpers, trouble, depth))

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    out = []
    out.append("# AUTO-GENERATED by tools/export_corpus_to_dsl.py.")
    out.append("# Do NOT hand-edit. Re-run the exporter to refresh.")
    out.append("#")
    out.append("# Each scenario is a corpus puzzle's initial state.")
    out.append("# Asserts that BFS solve produces a plan whose length")
    out.append("# matches Python's baseline depth distribution. Same")
    out.append("# fixture exercises Python (test_dsl_conformance.py)")
    out.append("# and Elm (DslConformanceTest.elm). Port-parity check.")
    out.append("")
    out.extend(scenarios)
    out.append("")  # trailing newline
    OUT_PATH.write_text("\n\n".join(out))
    print(f"wrote {OUT_PATH} ({len(scenarios)} scenarios)")


if __name__ == "__main__":
    main()
