// export_replay_walkthroughs.ts — auto-generate one
// `replay_invariant` DSL scenario per mined puzzle by reading
// pre-computed primitive sequences from
// `conformance/scenarios/verb_to_primitives_corpus.dsl` and
// concatenating each puzzle's plan-step primitives into a single
// action stream.
//
// Reads:  games/lynrummy/conformance/scenarios/verb_to_primitives_corpus.dsl
// Writes: games/lynrummy/conformance/scenarios/replay_walkthroughs.dsl
//
// Re-run after re-pinning corpus DSL scenarios. The exporter is a
// pure formatter — does not exercise verbs.ts or geometry_plan.ts;
// the corpus DSL is the source of truth.
//
// Usage:
//   node tools/export_replay_walkthroughs.ts

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const REPO = path.resolve(path.dirname(__filename), "..");
const SRC_DSL = path.join(
  REPO, "games/lynrummy/conformance/scenarios/verb_to_primitives_corpus.dsl");
const OUT_PATH = path.join(
  REPO, "games/lynrummy/conformance/scenarios/replay_walkthroughs.dsl");

// --- Minimal corpus-DSL parser (just what we need: name → board +
//     primitives, plus the puzzle/step parsed out of the name). ---

interface BoardLine { top: number; left: number; cards: string }
interface CorpusEntry {
  name: string;
  puzzle: string;
  step: number;
  boardLines: BoardLine[];
  primitives: string[];
}

/** Names follow `<puzzle>_step_<NN>`; the `_step_NN` suffix splits
 *  out the step number. (Matches how the JSON fixture named entries.) */
function splitName(name: string): { puzzle: string; step: number } {
  const m = name.match(/^(.+)_step_(\d+)$/);
  if (!m) throw new Error(`unexpected scenario name (no _step_NN): ${name}`);
  return { puzzle: m[1]!, step: parseInt(m[2]!, 10) };
}

function parse(contents: string): CorpusEntry[] {
  const out: CorpusEntry[] = [];
  const lines = contents.split("\n");
  let cur: CorpusEntry | null = null;
  let inBoard = false;
  let inPrimitives = false;

  for (const raw of lines) {
    const stripped = raw.replace(/#.*$/, "").trimEnd();
    const trimmed = stripped.trim();
    if (trimmed === "") continue;

    const sc = trimmed.match(/^scenario\s+(\S+)$/);
    if (sc && raw.match(/^scenario\b/)) {
      if (cur) out.push(cur);
      const { puzzle, step } = splitName(sc[1]!);
      cur = { name: sc[1]!, puzzle, step, boardLines: [], primitives: [] };
      inBoard = false;
      inPrimitives = false;
      continue;
    }
    if (cur === null) continue;

    if (trimmed === "board:") { inBoard = true; inPrimitives = false; continue; }
    if (trimmed === "primitives:") { inBoard = false; inPrimitives = true; continue; }
    if (trimmed === "expect:") { inBoard = false; inPrimitives = false; continue; }
    // Any other top-of-2-space `key:` ends an active block.
    if (raw.match(/^  [a-z_]+:/) && !raw.startsWith("    ")) {
      inBoard = false;
      inPrimitives = false;
    }

    if (inBoard) {
      const m = trimmed.match(/^at\s*\((-?\d+)\s*,\s*(-?\d+)\)\s*:\s*(.+)$/);
      if (m) cur.boardLines.push({
        top: parseInt(m[1]!, 10),
        left: parseInt(m[2]!, 10),
        cards: m[3]!.trim(),
      });
      continue;
    }
    if (inPrimitives) {
      const m = trimmed.match(/^-\s*(.+)$/);
      if (m) cur.primitives.push(m[1]!.trim());
      continue;
    }
  }
  if (cur) out.push(cur);
  return out;
}

// --- Render replay_walkthroughs scenario block ----------------------

function renderScenario(
  puzzle: string,
  initialBoard: readonly BoardLine[],
  actions: readonly string[],
): string {
  const lines: string[] = [];
  lines.push(`scenario walkthrough_${puzzle}`);
  lines.push(`  desc: Full agent-play walkthrough for ${puzzle}; eager + replay agree, final board victory.`);
  lines.push(`  op: replay_invariant`);
  lines.push(`  board:`);
  for (const b of initialBoard) {
    lines.push(`    at (${b.top},${b.left}): ${b.cards}`);
  }
  lines.push(`  actions:`);
  for (const a of actions) lines.push(`    - ${a}`);
  lines.push(`  expect:`);
  lines.push(`    final_board_victory: true`);
  return lines.join("\n");
}

function main(): void {
  const contents = fs.readFileSync(SRC_DSL, "utf8");
  const entries = parse(contents);

  // Group by puzzle, sort by step within.
  const byPuzzle = new Map<string, CorpusEntry[]>();
  for (const e of entries) {
    if (!byPuzzle.has(e.puzzle)) byPuzzle.set(e.puzzle, []);
    byPuzzle.get(e.puzzle)!.push(e);
  }
  for (const steps of byPuzzle.values()) steps.sort((a, b) => a.step - b.step);

  const header: string[] = [
    "# AUTO-GENERATED by tools/export_replay_walkthroughs.ts.",
    "# Do NOT hand-edit. Re-run the exporter to refresh.",
    "#",
    "# Source: conformance/scenarios/verb_to_primitives_corpus.dsl.",
    "# One scenario per mined puzzle — a full agent-play walkthrough",
    "# end-to-end. Each scenario asserts that the Replay FSM and the",
    "# eager applier agree on the final model AND that the puzzle ends",
    "# in victory.",
    "#",
    "# Hand-origin actions (MergeHand, PlaceHand) don't appear in",
    "# puzzle action logs — puzzles start with empty hands and the",
    "# agent only emits board-origin primitives.",
    "",
  ];

  const blocks: string[] = [];
  for (const puzzle of Array.from(byPuzzle.keys()).sort()) {
    const steps = byPuzzle.get(puzzle)!;
    const initialBoard = steps[0]!.boardLines;
    const actions: string[] = [];
    for (const s of steps) actions.push(...s.primitives);
    blocks.push(renderScenario(puzzle, initialBoard, actions));
  }

  const out = header.join("\n") + "\n" + blocks.join("\n\n") + "\n";
  fs.writeFileSync(OUT_PATH, out);
  console.log(`wrote ${path.relative(REPO, OUT_PATH)} (${blocks.length} scenarios)`);
}

main();
