"""
export_mined_to_dsl.py — emit the mined Puzzles as
DSL `solve` scenarios so cmd/fixturegen produces matching
Python + Elm conformance fixtures.

Same role as `export_corpus_to_dsl.py`, but sourced from
`games/lynrummy/conformance/mined_seeds.json` (the committed
file overwritten by `tools/mine_puzzles.py`).

Each scenario asserts the BFS plan_lines match Python's
canonical output — turning the mined catalog into a
cross-language regression test. The mined puzzles already
exercise the Elm UI (via the Puzzles gallery); promoting them
into the DSL pipeline catches verb/primitive drift that
plan-text-only conformance can miss (see the 2026-04-27
"two Aces" stall — Steel/set steal extract emitted one
fewer split in Elm than Python, undetected by existing
suite).

Pipeline:

    1. python3 tools/export_mined_to_dsl.py
    2. go run ./cmd/fixturegen \\
           ./games/lynrummy/conformance/scenarios/*.dsl
    3. python3 games/lynrummy/python/test_dsl_conformance.py
       cd games/lynrummy/elm && ./check.sh

Output: `games/lynrummy/conformance/scenarios/planner_mined.dsl`.
"""

import json
import sys
from pathlib import Path

REPO = Path("/home/steve/showell_repos/angry-gopher")
SEEDS_PATH = REPO / "games/lynrummy/conformance/mined_seeds.json"
OUT_PATH = REPO / "games/lynrummy/conformance/scenarios/planner_mined.dsl"

sys.path.insert(0, str(REPO / "games/lynrummy/python"))
import bfs  # noqa: E402
from rules import classify  # noqa: E402

RANKS = "A23456789TJQK"
SUITS = "CDSH"


def card_label_dsl(value, suit, deck):
    base = RANKS[value - 1] + SUITS[suit]
    return base + ("'" if deck else "")


def stacks_from_state(state):
    """Return list-of-tuple-stacks for the puzzle board."""
    out = []
    for stack in state["board"]:
        cards = [(bc["card"]["value"], bc["card"]["suit"],
                  bc["card"]["origin_deck"])
                 for bc in stack["board_cards"]]
        out.append(cards)
    return out


def split_helper_trouble(board):
    """Mirror `bfs.solve`'s classification: any stack that
    classify() reports as 'other' is trouble; the rest are
    helper. Mined puzzles only have helper + trouble (no
    pre-existing growing/complete), matching corpus initial
    states."""
    helper = [s for s in board if classify(s) != "other"]
    trouble = [s for s in board if classify(s) == "other"]
    return helper, trouble


def render_scenario(name, helper, trouble, plan):
    lines = [
        f"scenario mined_{name}",
        f"  desc: Mined puzzle {name}. Auto-generated; do not hand-edit.",
        "  op: solve",
        "  helper:",
    ]
    for stack in helper:
        labels = " ".join(card_label_dsl(*c) for c in stack)
        lines.append(f"    at (0,0): {labels}")
    lines.append("  trouble:")
    for stack in trouble:
        labels = " ".join(card_label_dsl(*c) for c in stack)
        lines.append(f"    at (0,0): {labels}")
    if plan is None:
        lines.append("  expect: no_plan")
    else:
        lines.append("  expect:")
        lines.append("    plan_lines:")
        for line in plan:
            lines.append(f"      - {json.dumps(line)}")
    return "\n".join(lines)


def main():
    with open(SEEDS_PATH) as f:
        seeds = json.load(f)["seeds"]
    seeds = sorted(seeds, key=lambda s: s["puzzle_name"])

    scenarios = []
    for seed in seeds:
        puzzle_name = seed["puzzle_name"]
        state = seed["initial_state"]
        board = stacks_from_state(state)
        helper, trouble = split_helper_trouble(board)
        plan = bfs.solve(board, max_trouble_outer=10,
                         max_states=200000, verbose=False)
        scenarios.append(render_scenario(
            puzzle_name, helper, trouble, plan))

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    out = [
        "# AUTO-GENERATED by tools/export_mined_to_dsl.py.",
        "# Do NOT hand-edit. Re-run the exporter to refresh.",
        "#",
        "# Each scenario is one mined Puzzles puzzle's initial",
        "# state. Asserts that BFS solve produces a plan whose",
        "# lines match Python's canonical output. Runs in both",
        "# `test_dsl_conformance.py` (Python) and",
        "# `DslConformanceTest.elm` (Elm).",
        "",
    ]
    out.extend(scenarios)
    out.append("")
    OUT_PATH.write_text("\n\n".join(out))
    print(f"wrote {OUT_PATH} ({len(scenarios)} scenarios)")


if __name__ == "__main__":
    main()
