"""
export_corpus_to_dsl.py — emit the BFS corpus as DSL
scenarios so cmd/fixturegen can generate matching Python +
Elm conformance fixtures.

The corpus is the 21 puzzle sessions the human/agent ran
through `corpus/sessions.txt`. Each puzzle's initial state
becomes one `solve` scenario asserting the BFS plan-length
matches Python's baseline (the depth distribution from
the post-focus-rule + SPLIT_OUT solver).

This unifies what was a Python-only `corpus_report.py`
correctness check into the cross-language DSL pipeline:

    1. python3 tools/export_corpus_to_dsl.py
    2. go run ./cmd/fixturegen \\
           ./games/lynrummy/conformance/scenarios/*.dsl
    3. python3 games/lynrummy/python/test_dsl_conformance.py
       cd games/lynrummy/elm && ./check.sh

Both runners now assert the corpus depths.

Output goes to `games/lynrummy/conformance/scenarios/
planner_corpus.dsl` (separate from hand-authored
`planner.dsl` so the gen vs hand boundary stays clean).
"""

import json
import sqlite3
import sys
from pathlib import Path

DB_PATH = "/home/steve/AngryGopher/prod/gopher.db"
REPO = Path("/home/steve/showell_repos/angry-gopher")
SESSIONS_PATH = REPO / "games/lynrummy/python/corpus/sessions.txt"
OUT_PATH = REPO / "games/lynrummy/conformance/scenarios/planner_corpus.dsl"

# Need the BFS solver to produce canonical plan_lines.
sys.path.insert(0, str(REPO / "games/lynrummy/python"))
import bfs  # noqa: E402

RANKS = "A23456789TJQK"
SUITS = "CDSH"


def card_label_dsl(value, suit, deck):
    """DSL-style label: '5H' for deck-0, '5D'' for deck-1."""
    base = RANKS[value - 1] + SUITS[suit]
    return base + ("'" if deck else "")


def board_for_solver(state):
    """Return (helper_stacks_labels, helper_stacks_tuples,
    trouble_label, trouble_tuple). Labels are for DSL output;
    tuples are for feeding bfs.solve to capture canonical
    plan_lines."""
    helpers_labels = []
    helpers_tuples = []
    for stack in state["board"]:
        cards = [(bc["card"]["value"], bc["card"]["suit"],
                  bc["card"]["origin_deck"])
                 for bc in stack["board_cards"]]
        helpers_tuples.append(cards)
        helpers_labels.append(
            [card_label_dsl(*c) for c in cards])
    hand = state["hands"][state["active_player_index"]]["hand_cards"]
    tc = hand[0]["card"]
    trouble_tuple = (tc["value"], tc["suit"], tc["origin_deck"])
    trouble_label = card_label_dsl(*trouble_tuple)
    return helpers_labels, helpers_tuples, trouble_label, trouble_tuple


def canonical_plan_lines(helpers_tuples, trouble_tuple):
    """Run Python's BFS on the augmented board and return
    the exact plan-line strings (or None if no plan)."""
    augmented = list(helpers_tuples) + [[trouble_tuple]]
    plan = bfs.solve(augmented, max_trouble_outer=10,
                     max_states=200000, verbose=False)
    return plan


def render_scenario(sid, helpers, trouble, plan):
    """Emit one DSL scenario.

    `plan` is None for unsolvable puzzles (becomes
    `expect: no_plan`) or a list of plan-line strings
    (becomes `expect: plan_lines: [...]`)."""
    lines = []
    lines.append(f"scenario corpus_sid_{sid}")
    lines.append(
        f"  desc: Corpus session {sid}, trouble {trouble}. "
        "Auto-generated; do not hand-edit.")
    lines.append("  op: solve")
    lines.append("  helper:")
    for stack in helpers:
        lines.append(f"    at (0,0): {' '.join(stack)}")
    lines.append("  trouble:")
    lines.append(f"    at (0,0): {trouble}")
    if plan is None:
        lines.append("  expect: no_plan")
    else:
        lines.append("  expect:")
        lines.append("    plan_lines:")
        for line in plan:
            # Quote via JSON so embedded chars (→, etc.)
            # round-trip cleanly.
            lines.append(f"      - {json.dumps(line)}")
    return "\n".join(lines)


def main():
    sids = [int(s.strip()) for s in open(SESSIONS_PATH) if s.strip()]

    conn = sqlite3.connect(DB_PATH)
    scenarios = []
    for sid in sids:
        row = conn.execute(
            "SELECT initial_state_json FROM lynrummy_puzzle_seeds "
            "WHERE session_id=?", (sid,)).fetchone()
        state = json.loads(row[0])
        helpers_labels, helpers_tuples, trouble_label, trouble_tuple = \
            board_for_solver(state)
        plan = canonical_plan_lines(helpers_tuples, trouble_tuple)
        scenarios.append(render_scenario(
            sid, helpers_labels, trouble_label, plan))

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    out = []
    out.append("# AUTO-GENERATED by tools/export_corpus_to_dsl.py.")
    out.append("# Do NOT hand-edit. Re-run the exporter to refresh.")
    out.append("#")
    out.append("# Each scenario is a corpus puzzle's initial state.")
    out.append("# Asserts that BFS solve produces a plan whose length")
    out.append("# matches Python's baseline depth distribution. Same")
    out.append("# fixture exercises Python (test_dsl_conformance.py)")
    out.append("# and Elm (DslConformanceTest.elm). Port-parity check.")
    out.append("")
    out.extend(scenarios)
    out.append("")  # trailing newline
    OUT_PATH.write_text("\n\n".join(out))
    print(f"wrote {OUT_PATH} ({len(scenarios)} scenarios)")


if __name__ == "__main__":
    main()
