"""
export_replay_walkthroughs.py — auto-generate one
`replay_invariant` DSL scenario per mined puzzle.

The 25 mined puzzles each have a known BFS plan. Each plan
step has a known canonical primitive sequence (already in
`primitives_fixtures.json`). Concatenating those sequences
gives the full agent-play action log for the puzzle.

For each puzzle this emits a DSL scenario that:

  1. Builds the initial Play.Model from the puzzle's board.
  2. Runs the eager applier over the full action list.
  3. Runs the Replay FSM forward to completion over the
     same actions.
  4. Asserts (eagerModel == replayedModel) AND that the
     final board is victory (every stack a complete group).

That's the headache-prevention gate for the click-Let-agent-
play flow: if all 25 walkthroughs pass, the user-visible
playback works end-to-end.

Reads:  games/lynrummy/conformance/primitives_fixtures.json
Writes: games/lynrummy/conformance/scenarios/replay_walkthroughs.dsl

Re-run after any change that affects what the walkthrough
should expect. Note: the upstream primitives-fixture exporter
retired 2026-05-02 with the BFS-retirement work — the JSON
fixtures are now committed-and-static. Resurrect from git
history if a future Elm BFS resurrection requires regen.
"""

import json
from pathlib import Path

REPO = Path("/home/steve/showell_repos/angry-gopher")
FIXTURES_PATH = REPO / "games/lynrummy/conformance/primitives_fixtures.json"
OUT_PATH = REPO / "games/lynrummy/conformance/scenarios/replay_walkthroughs.dsl"


def main():
    fixtures = json.loads(FIXTURES_PATH.read_text())

    # Group by puzzle, sort steps within each.
    by_puzzle = {}
    for f in fixtures:
        by_puzzle.setdefault(f["puzzle"], []).append(f)
    for steps in by_puzzle.values():
        steps.sort(key=lambda x: x["step"])

    scenarios = []
    for puzzle_name in sorted(by_puzzle.keys()):
        steps = by_puzzle[puzzle_name]
        initial_board = steps[0]["board_before"]
        actions = []
        for s in steps:
            actions.extend(s["expect_primitives"])
        scenarios.append((puzzle_name, initial_board, actions))

    out = [
        "# AUTO-GENERATED by tools/export_replay_walkthroughs.py.",
        "# Do NOT hand-edit. Re-run the exporter to refresh.",
        "#",
        "# One scenario per mined puzzle — a full agent-play",
        "# walkthrough end-to-end. Each scenario asserts that",
        "# the Replay FSM and the eager applier agree on the",
        "# final model AND that the puzzle ends in victory.",
        "#",
        "# Hand-origin actions (MergeHand, PlaceHand) don't",
        "# appear in puzzle action logs — puzzles start with",
        "# empty hands and the agent only emits board-origin",
        "# primitives. So this op is sufficient coverage even",
        "# though Replay's hand-rect path can't run under",
        "# elm-test.",
        "",
    ]
    for puzzle_name, board, actions in scenarios:
        out.append(render_scenario(puzzle_name, board, actions))
        out.append("")

    OUT_PATH.write_text("\n".join(out))
    print(f"wrote {OUT_PATH} ({len(scenarios)} scenarios)")


def render_scenario(puzzle_name, board, actions):
    lines = [
        f"scenario walkthrough_{puzzle_name}",
        f"  desc: Full agent-play walkthrough for {puzzle_name}; eager + replay agree, final board victory.",
        "  op: replay_invariant",
        "  board:",
    ]
    for stack in board:
        labels = " ".join(stack["cards"])
        top, left = stack["loc"]
        lines.append(f"    at ({top},{left}): {labels}")
    lines.append("  actions:")
    for a in actions:
        lines.append(f"    - {a}")
    lines.append("  expect:")
    lines.append("    final_board_victory: true")
    return "\n".join(lines)


if __name__ == "__main__":
    main()
