#!/usr/bin/env -S node --no-warnings --experimental-strip-types
// embed_dsls_for_elm.ts — read every .dsl in games/lynrummy/
// conformance/scenarios/ and emit an Elm module whose
// `allFiles` is a List (String, String) of (basename,
// contents). The Elm-side conformance test parses each
// entry at test time via Game.ConformanceDsl.parseConformanceDsl.
//
// Embeds each .dsl as a raw string so the Elm-side parser
// can run at test time — no codegen.

import * as fs from "node:fs";
import * as path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const DSL_DIR = path.join(ROOT, "games/lynrummy/conformance/scenarios");
const OUT = path.join(ROOT, "games/lynrummy/elm/tests/Lib/DslContent.elm");

function escapeForElm(s: string): string {
  // Elm triple-quoted strings: backslash and triple-quote are the
  // only sequences that need escaping.
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"""/g, '"\\"\\"');
}

function main(): void {
  const files = fs
    .readdirSync(DSL_DIR)
    .filter(f => f.endsWith(".dsl"))
    .sort();

  if (files.length === 0) {
    throw new Error(`no .dsl files found in ${DSL_DIR}`);
  }

  const entries = files.map((f, i) => {
    const text = fs.readFileSync(path.join(DSL_DIR, f), "utf8");
    const prefix = i === 0 ? "    [ " : "    , ";
    return `${prefix}( ${JSON.stringify(f)}\n      , """${escapeForElm(text)}"""\n      )`;
  });

  const out =
    `module Lib.DslContent exposing (allFiles)\n` +
    `\n` +
    `{-| GENERATED by ops/embed_dsls_for_elm.ts — DO NOT EDIT.\n` +
    `Re-run that script (or ops/test_elm) when .dsl files\n` +
    `change.\n` +
    `\n` +
    `Each entry is (basename, file contents). The Elm-side\n` +
    `conformance test parses each at test time via\n` +
    `Lib.ConformanceDsl.parseConformanceDsl.\n` +
    `-}\n` +
    `\n` +
    `\n` +
    `allFiles : List ( String, String )\n` +
    `allFiles =\n` +
    entries.join("\n") + "\n" +
    `    ]\n`;

  fs.writeFileSync(OUT, out);
  console.log(`Embedded ${files.length} .dsl files → ${path.relative(ROOT, OUT)}`);
}

main();
