// goldgen.ts — generate the cross-language GOLD CORPUS for the zig solver port.
// Not in the browser bundle; run from the repo root:
//
//   delivery/node_modules/.bin/esbuild delivery/goldgen.ts \
//     --bundle --platform=node --format=esm --outfile=/tmp/gg.mjs && node /tmp/gg.mjs
//
// Writes delivery/solver_gold.json: the first 20 shifts of the UI's seed chain
// (S1..S20 from seed 49), each pinned down to
//
//   - the demand draw (per-neighborhood house-index lists) — catches a bad port
//     of chooseOrders/mulberry32 BEFORE any solver code is suspected,
//   - every race variant's pain and the winner label — localizes a divergence
//     to one runSolve configuration,
//   - the winning plan's full route structure (per truck slot: ordered stops,
//     house indices, pins) and per-route pain integers.
//
// Everything pinned is INTEGER or structural — no floats — so a zig port must
// match it BIT-FOR-BIT; any tolerance would only hide a port bug. Display
// times (Plan.totalTime/travel/local) are float geometry and deliberately NOT
// pinned. The file is deterministic: regenerating it must produce an identical
// byte stream (no timestamps), so `git diff` after a regen is the whole story.
//
// Legality is asserted (solver_check.ts's invariants) before writing: a gold
// file is only worth having if the plans in it are legal.

import { writeFileSync } from "node:fs";
import { buildSubstrate, edges } from "./roadgraph.ts";
import { race, painOf, planPain, RACE } from "./solver.ts";
import { chooseOrders, ordersByNeighborhood } from "./orders.ts";
import { FLEET, TRUCK_ANCHORS, TRUCK_CAPS } from "./geography.ts";

const N_SHIFTS = 20;
const sub = buildSubstrate();

// The same LCG the UI walks shift to shift (main.ts).
function shiftSeeds(n: number): number[] {
  const seeds: number[] = [];
  let seed = 49;
  for (let i = 0; i < n; i++) {
    seeds.push(seed);
    seed = (seed * 1664525 + 1013904223) >>> 0;
  }
  return seeds;
}

function assert(ok: boolean, msg: string): void {
  if (!ok) throw new Error(`gold corpus ILLEGAL, not writing: ${msg}`);
}

type GoldStop = { nbhd: string; houses: number[]; pin?: number };
type GoldRoute = { stops: GoldStop[]; orders: number; pain: number };
type GoldShift = {
  shift: number;
  seed: number;
  demand: [string, number[]][]; // nbhd -> ordered house indices, sorted by name
  race: { winner: string; pains: { label: string; pain: number }[] };
  routes: GoldRoute[]; // one per truck slot, in slot order; empty stops = idle
  totalPain: number;
};

const shifts: GoldShift[] = [];
for (const [i, seed] of shiftSeeds(N_SHIFTS).entries()) {
  const orders = chooseOrders(seed, FLEET.orders);
  const byNbhd = ordersByNeighborhood(orders);
  const { best: plan, winner, pains } = race(sub, byNbhd);

  // Legality (mirrors solver_check.ts) — fail loud, write nothing.
  const totalOrders = [...byNbhd.values()].reduce((s, v) => s + v.length, 0);
  const planned = plan.routes.reduce((s, r) => s + r.orders, 0);
  assert(plan.routes.length === FLEET.trucks, `seed ${seed}: ${plan.routes.length} routes ≠ ${FLEET.trucks} slots`);
  assert(plan.unrouted.length === 0, `seed ${seed}: ${plan.unrouted.length} stops unrouted`);
  assert(planned === totalOrders, `seed ${seed}: planned ${planned} ≠ ${totalOrders} ordered`);
  plan.routes.forEach((r, slot) => assert(r.orders <= TRUCK_CAPS[slot], `seed ${seed}: truck ${slot + 1} over cap (${r.orders} > ${TRUCK_CAPS[slot]})`));
  TRUCK_ANCHORS.forEach((name, slot) => {
    if (byNbhd.has(name)) assert(plan.routes[slot].stops.some((s) => s.nbhd === name), `seed ${seed}: truck ${slot + 1} lost its anchor ${name}`);
  });

  shifts.push({
    shift: i + 1,
    seed,
    demand: [...byNbhd.entries()].sort(([a], [b]) => (a < b ? -1 : 1)).map(([n, h]) => [n, h]),
    race: { winner, pains },
    routes: plan.routes.map((r) => ({
      stops: r.stops.map((s) => (s.pin === undefined ? { nbhd: s.nbhd, houses: s.houses } : { nbhd: s.nbhd, houses: s.houses, pin: s.pin })),
      orders: r.orders,
      pain: painOf(sub, r.stops),
    })),
    totalPain: planPain(sub, plan),
  });
}

// The substrate, pinned as its own oracle layer: a zig divergence in `edges`
// is a geometry/rounding port bug, in `matrix` a Dijkstra bug, in `paths` a
// tie-break bug (first-min selection + strict-< relaxation order) — each
// caught before a single solver line is suspected. Paths are pinned for every
// ordered pair (pathNodes consults them; equal-cost alternates are resolved
// by iteration order, so they're semantics, not detail).
const substrate = {
  nodes: sub.nodes,
  edges: edges(),
  matrix: sub.matrix,
  paths: sub.nodes.map((a) => sub.nodes.map((b) => sub.path(a, b))),
};

const gold = {
  _what:
    "GOLD CORPUS for the TS→zig solver port. Generated by delivery/goldgen.ts from the TS solver " +
    "(the reference implementation). The zig port must reproduce every integer and every structure " +
    "here BIT-FOR-BIT — strict equality, no tolerances. Regenerate ONLY when the TS solver itself " +
    "changes semantics, and expect the diff to say exactly what moved.",
  fleet: { trucks: FLEET.trucks, orders: FLEET.orders, caps: TRUCK_CAPS, anchors: TRUCK_ANCHORS },
  raceVariants: RACE.map((v) => v.label),
  substrate,
  shifts,
};

writeFileSync("delivery/solver_gold.json", JSON.stringify(gold, null, 1) + "\n");
console.log(`wrote delivery/solver_gold.json: ${shifts.length} shifts, total pain ${shifts.reduce((s, d) => s + d.totalPain, 0)}`);
console.log(`winners: ${shifts.map((d) => d.race.winner).join(", ")}`);

// --- The frames/display gold — a second file so the core corpus stays lean.
// Pins the browser-facing HALF of the Plan: the solve-replay frames (labels,
// touched house keys, full route snapshots — everything the `A` stepper draws)
// and the display numbers (route time/travel, plan totals, spread). Integers
// and strings are strict; the float fields (local/time/totalTime/spread pass
// through trig) are pinned at full precision and the zig side compares them
// with an ULP-scale tolerance — engine libm variance, not semantics.
const framesGold = {
  _what:
    "FRAMES + DISPLAY GOLD for the TS→zig solver port — the Plan surface the browser consumes " +
    "beyond route structure. Generated by delivery/goldgen.ts; same regeneration rule as solver_gold.json.",
  shifts: shiftSeeds(N_SHIFTS).map((seed, i) => {
    const orders = chooseOrders(seed, FLEET.orders);
    const plan = race(sub, ordersByNeighborhood(orders)).best;
    return {
      shift: i + 1,
      seed,
      routes: plan.routes.map((r) => ({ orders: r.orders, travel: r.travel, time: r.time })),
      totalTime: plan.totalTime,
      travel: plan.travel,
      local: plan.local,
      service: plan.service,
      spread: plan.spread,
      frames: plan.frames,
    };
  }),
};
writeFileSync("delivery/solver_frames_gold.json", JSON.stringify(framesGold) + "\n");
const nframes = framesGold.shifts.reduce((s, d) => s + d.frames.length, 0);
console.log(`wrote delivery/solver_frames_gold.json: ${nframes} frames across ${framesGold.shifts.length} shifts`);
