-- GENERATED by cmd/fixturegen — DO NOT EDIT.
-- Source scenarios: lynrummy/conformance/scenarios/*.dsl
-- Regenerate with: go run ./cmd/fixturegen ./lynrummy/conformance/scenarios/*.dsl

module LynRummy.DslConformanceTest exposing (suite)

import Expect
import LynRummy.BoardGeometry exposing (BoardBounds)
import LynRummy.Card exposing (Card, CardValue(..), OriginDeck(..), Suit(..))
import LynRummy.CardStack
    exposing
        ( BoardCard
        , BoardCardState(..)
        , BoardLocation
        , CardStack
        , HandCard
        , HandCardState(..)
        )
import LynRummy.Referee as Referee exposing (RefereeStage(..), refereeStageToString)
import LynRummy.Tricks.DirectPlay
import LynRummy.Tricks.HandStacks
import LynRummy.Tricks.Hint as Hint
import LynRummy.Tricks.LooseCardPlay
import LynRummy.Tricks.PairPeel
import LynRummy.Tricks.PeelForRun
import LynRummy.Tricks.RbSwap
import LynRummy.Tricks.SplitForSet
import Test exposing (Test, describe, test)


standardBounds : BoardBounds
standardBounds =
    { maxWidth = 800, maxHeight = 600, margin = 5 }



deckIdentityMismatchInRemove : Test
deckIdentityMismatchInRemove =
    test "deck_identity_mismatch_in_remove" <|
        \_ ->
            let
                move =
                    { boardBefore = [ { boardCards = [ { card = { value = Five, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 10, left = 10 } }
                        ]
                    , stacksToRemove = [ { boardCards = [ { card = { value = Five, suit = Heart, originDeck = DeckTwo }, state = FirmlyOnBoard }, { card = { value = Six, suit = Heart, originDeck = DeckTwo }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Heart, originDeck = DeckTwo }, state = FirmlyOnBoard } ], loc = { top = 10, left = 10 } }
                        ]
                    , stacksToAdd = [ { boardCards = [ { card = { value = Five, suit = Heart, originDeck = DeckTwo }, state = FirmlyOnBoard }, { card = { value = Six, suit = Heart, originDeck = DeckTwo }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Heart, originDeck = DeckTwo }, state = FirmlyOnBoard }, { card = { value = Eight, suit = Heart, originDeck = DeckTwo }, state = FreshlyPlayed } ], loc = { top = 10, left = 10 } }
                        ]
                    , handCardsPlayed = [ { card = { value = Eight, suit = Heart, originDeck = DeckTwo }, state = HandNormal } ]
                    }
            in
            case Referee.validateGameMove move standardBounds of
                Ok _ ->
                    Expect.fail ("expected error at stage " ++ "inventory" ++ ", got ok")

                Err err ->
                    if refereeStageToString err.stage /= "inventory" then
                        Expect.fail ("stage: want " ++ "inventory" ++ ", got " ++ refereeStageToString err.stage)
                    else if not (String.contains "not on the board" err.message) then
                        Expect.fail ("message substring " ++ "not on the board" ++ " not found in " ++ err.message)
                    else
                        Expect.pass


geometryCrowded : Test
geometryCrowded =
    test "geometry_crowded" <|
        \_ ->
            let
                move =
                    { boardBefore = []
                    , stacksToRemove = []
                    , stacksToAdd = [ { boardCards = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 10, left = 10 } }
                        , { boardCards = [ { card = { value = Two, suit = Spade, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 10, left = 40 } }
                        ]
                    , handCardsPlayed = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = HandNormal }, { card = { value = Two, suit = Spade, originDeck = DeckOne }, state = HandNormal } ]
                    }
            in
            case Referee.validateGameMove move standardBounds of
                Ok _ ->
                    Expect.fail ("expected error at stage " ++ "geometry" ++ ", got ok")

                Err err ->
                    if refereeStageToString err.stage /= "geometry" then
                        Expect.fail ("stage: want " ++ "geometry" ++ ", got " ++ refereeStageToString err.stage)
                    else if not (String.contains "too close" err.message) then
                        Expect.fail ("message substring " ++ "too close" ++ " not found in " ++ err.message)
                    else
                        Expect.pass


geometryOutOfBounds : Test
geometryOutOfBounds =
    test "geometry_out_of_bounds" <|
        \_ ->
            let
                move =
                    { boardBefore = []
                    , stacksToRemove = []
                    , stacksToAdd = [ { boardCards = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 10, left = 790 } }
                        ]
                    , handCardsPlayed = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = HandNormal } ]
                    }
            in
            case Referee.validateGameMove move standardBounds of
                Ok _ ->
                    Expect.fail ("expected error at stage " ++ "geometry" ++ ", got ok")

                Err err ->
                    if refereeStageToString err.stage /= "geometry" then
                        Expect.fail ("stage: want " ++ "geometry" ++ ", got " ++ refereeStageToString err.stage)
                    else if not (String.contains "outside" err.message) then
                        Expect.fail ("message substring " ++ "outside" ++ " not found in " ++ err.message)
                    else
                        Expect.pass


geometryOverlap : Test
geometryOverlap =
    test "geometry_overlap" <|
        \_ ->
            let
                move =
                    { boardBefore = []
                    , stacksToRemove = []
                    , stacksToAdd = [ { boardCards = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 10, left = 10 } }
                        , { boardCards = [ { card = { value = Two, suit = Spade, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 10, left = 10 } }
                        ]
                    , handCardsPlayed = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = HandNormal }, { card = { value = Two, suit = Spade, originDeck = DeckOne }, state = HandNormal } ]
                    }
            in
            case Referee.validateGameMove move standardBounds of
                Ok _ ->
                    Expect.fail ("expected error at stage " ++ "geometry" ++ ", got ok")

                Err err ->
                    if refereeStageToString err.stage /= "geometry" then
                        Expect.fail ("stage: want " ++ "geometry" ++ ", got " ++ refereeStageToString err.stage)
                    else if not (String.contains "overlap" err.message) then
                        Expect.fail ("message substring " ++ "overlap" ++ " not found in " ++ err.message)
                    else
                        Expect.pass


hintDirectPlayWinsPriorityOnOpeningBoard : Test
hintDirectPlayWinsPriorityOnOpeningBoard =
    test "hint_direct_play_wins_priority_on_opening_board" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Seven, suit = Heart, originDeck = DeckTwo }, state = HandNormal } ]

                hand =
                    { handCards = handCards }

                board =
                    [ { boardCards = [ { card = { value = King, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Ace, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Two, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 70, left = 20 } }
                        , { boardCards = [ { card = { value = Ten, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Jack, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Queen, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = King, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 160, left = 80 } }
                        , { boardCards = [ { card = { value = Two, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Four, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 100, left = 140 } }
                        , { boardCards = [ { card = { value = Seven, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 40, left = 200 } }
                        , { boardCards = [ { card = { value = Ace, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Ace, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 130, left = 260 } }
                        , { boardCards = [ { card = { value = Two, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Four, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Five, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 70, left = 320 } }
                        ]

                got =
                    Hint.buildSuggestions hand board
            in
            if List.length got /= 1 then
                Expect.fail ("suggestion count: want 1, got " ++ String.fromInt (List.length got))

            else
                let
                    want0 =
                        { trickId = "direct_play", handCards = [ { value = Seven, suit = Heart, originDeck = DeckTwo } ] }

                in
                Expect.all
                    [ \_ -> List.drop 0 got |> List.head |> Maybe.map (\s -> { trickId = s.trickId, handCards = s.handCards }) |> Expect.equal (Just want0)
                    ]
                    ()


hintEmptyHandNoSuggestions : Test
hintEmptyHandNoSuggestions =
    test "hint_empty_hand_no_suggestions" <|
        \_ ->
            let
                handCards =
                    []

                hand =
                    { handCards = handCards }

                board =
                    [ { boardCards = [ { card = { value = King, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Ace, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Two, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 70, left = 20 } }
                        , { boardCards = [ { card = { value = Ten, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Jack, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Queen, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = King, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 160, left = 80 } }
                        , { boardCards = [ { card = { value = Two, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Four, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 100, left = 140 } }
                        ]

                got =
                    Hint.buildSuggestions hand board
            in
            if List.length got /= 0 then
                Expect.fail ("suggestion count: want 0, got " ++ String.fromInt (List.length got))

            else
                Expect.pass


hintNoPlaysForLonelyUnplayableCard : Test
hintNoPlaysForLonelyUnplayableCard =
    test "hint_no_plays_for_lonely_unplayable_card" <|
        \_ ->
            let
                handCards =
                    [ { card = { value = Nine, suit = Spade, originDeck = DeckOne }, state = HandNormal } ]

                hand =
                    { handCards = handCards }

                board =
                    [ { boardCards = [ { card = { value = Two, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Four, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 70, left = 20 } }
                        ]

                got =
                    Hint.buildSuggestions hand board
            in
            if List.length got /= 0 then
                Expect.fail ("suggestion count: want 0, got " ++ String.fromInt (List.length got))

            else
                Expect.pass


inventoryCardFromNowhere : Test
inventoryCardFromNowhere =
    test "inventory_card_from_nowhere" <|
        \_ ->
            let
                move =
                    { boardBefore = []
                    , stacksToRemove = []
                    , stacksToAdd = [ { boardCards = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = FreshlyPlayed }, { card = { value = Two, suit = Heart, originDeck = DeckOne }, state = FreshlyPlayed }, { card = { value = Three, suit = Heart, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 10, left = 10 } }
                        ]
                    , handCardsPlayed = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = HandNormal }, { card = { value = Two, suit = Heart, originDeck = DeckOne }, state = HandNormal } ]
                    }
            in
            case Referee.validateGameMove move standardBounds of
                Ok _ ->
                    Expect.fail ("expected error at stage " ++ "inventory" ++ ", got ok")

                Err err ->
                    if refereeStageToString err.stage /= "inventory" then
                        Expect.fail ("stage: want " ++ "inventory" ++ ", got " ++ refereeStageToString err.stage)
                    else if not (String.contains "no source" err.message) then
                        Expect.fail ("message substring " ++ "no source" ++ " not found in " ++ err.message)
                    else
                        Expect.pass


midturnAllowsBogus : Test
midturnAllowsBogus =
    test "midturn_allows_bogus" <|
        \_ ->
            let
                move =
                    { boardBefore = []
                    , stacksToRemove = []
                    , stacksToAdd = [ { boardCards = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = FreshlyPlayed }, { card = { value = Five, suit = Club, originDeck = DeckOne }, state = FreshlyPlayed }, { card = { value = King, suit = Diamond, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 10, left = 10 } }
                        ]
                    , handCardsPlayed = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = HandNormal }, { card = { value = Five, suit = Club, originDeck = DeckOne }, state = HandNormal }, { card = { value = King, suit = Diamond, originDeck = DeckOne }, state = HandNormal } ]
                    }
            in
            case Referee.validateGameMove move standardBounds of
                Ok _ ->
                    Expect.pass

                Err err ->
                    Expect.fail (refereeStageToString err.stage ++ ": " ++ err.message)


turnCompleteCleanBoard : Test
turnCompleteCleanBoard =
    test "turn_complete_clean_board" <|
        \_ ->
            let
                board =
                    [ { boardCards = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Two, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Three, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 10, left = 10 } }
                    , { boardCards = [ { card = { value = King, suit = Club, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = King, suit = Diamond, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = King, suit = Spade, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 10, left = 200 } }
                    ]
            in
            case Referee.validateTurnComplete board standardBounds of
                Ok _ ->
                    Expect.pass

                Err err ->
                    Expect.fail (refereeStageToString err.stage ++ ": " ++ err.message)


turnCompleteRejectsIncomplete : Test
turnCompleteRejectsIncomplete =
    test "turn_complete_rejects_incomplete" <|
        \_ ->
            let
                board =
                    [ { boardCards = [ { card = { value = Ace, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Two, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 10, left = 10 } }
                    ]
            in
            case Referee.validateTurnComplete board standardBounds of
                Ok _ ->
                    Expect.fail ("expected error at stage " ++ "semantics" ++ ", got ok")

                Err err ->
                    if refereeStageToString err.stage /= "semantics" then
                        Expect.fail ("stage: want " ++ "semantics" ++ ", got " ++ refereeStageToString err.stage)
                    else if not (String.contains "incomplete" err.message) then
                        Expect.fail ("message substring " ++ "incomplete" ++ " not found in " ++ err.message)
                    else
                        Expect.pass


validExtendRunWith8H : Test
validExtendRunWith8H =
    test "valid_extend_run_with_8H" <|
        \_ ->
            let
                move =
                    { boardBefore = [ { boardCards = [ { card = { value = Five, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 10, left = 10 } }
                        ]
                    , stacksToRemove = [ { boardCards = [ { card = { value = Five, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard } ], loc = { top = 10, left = 10 } }
                        ]
                    , stacksToAdd = [ { boardCards = [ { card = { value = Five, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Six, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Seven, suit = Heart, originDeck = DeckOne }, state = FirmlyOnBoard }, { card = { value = Eight, suit = Heart, originDeck = DeckOne }, state = FreshlyPlayed } ], loc = { top = 10, left = 10 } }
                        ]
                    , handCardsPlayed = [ { card = { value = Eight, suit = Heart, originDeck = DeckOne }, state = HandNormal } ]
                    }
            in
            case Referee.validateGameMove move standardBounds of
                Ok _ ->
                    Expect.pass

                Err err ->
                    Expect.fail (refereeStageToString err.stage ++ ": " ++ err.message)


suite : Test
suite =
    describe "DSL conformance"
        [ deckIdentityMismatchInRemove
        , geometryCrowded
        , geometryOutOfBounds
        , geometryOverlap
        , hintDirectPlayWinsPriorityOnOpeningBoard
        , hintEmptyHandNoSuggestions
        , hintNoPlaysForLonelyUnplayableCard
        , inventoryCardFromNowhere
        , midturnAllowsBogus
        , turnCompleteCleanBoard
        , turnCompleteRejectsIncomplete
        , validExtendRunWith8H
        ]
